package com.coolerpromc.ancientcreature.client.entity.animation.block;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

// Generated by art/texgen/machines/make_machines.py from art/texgen/machines/defs/fossil_cleaning_table.py - edit that, not this file.
public final class FossilCleaningTableAnimation {
    public static final AnimationDefinition PROCESSING = AnimationDefinition.Builder.withLength(1.6F).looping()
        .addAnimation("brush", new AnimationChannel(AnimationChannel.Targets.POSITION,
            new Keyframe(0F, KeyframeAnimations.posVec(-1.6F, 0.35F, 0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.12F, KeyframeAnimations.posVec(-1.6F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.62F, KeyframeAnimations.posVec(1.7F, 0F, 0.2F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.posVec(1.7F, 0.45F, 0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.92F, KeyframeAnimations.posVec(-1.6F, 0.35F, 0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.04F, KeyframeAnimations.posVec(-1.6F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.42F, KeyframeAnimations.posVec(1.7F, 0F, -0.2F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.6F, KeyframeAnimations.posVec(-1.6F, 0.35F, 0F), AnimationChannel.Interpolations.CATMULLROM)
        ))
        .addAnimation("brush", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 12F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.12F, KeyframeAnimations.degreeVec(0F, 0F, 8F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.62F, KeyframeAnimations.degreeVec(0F, 0F, -14F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.8F, KeyframeAnimations.degreeVec(0F, 0F, -6F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.92F, KeyframeAnimations.degreeVec(0F, 0F, 12F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.04F, KeyframeAnimations.degreeVec(0F, 0F, 8F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.42F, KeyframeAnimations.degreeVec(0F, 0F, -14F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.6F, KeyframeAnimations.degreeVec(0F, 0F, 12F), AnimationChannel.Interpolations.CATMULLROM)
        ))
        .addAnimation("dust", new AnimationChannel(AnimationChannel.Targets.POSITION,
            new Keyframe(0F, KeyframeAnimations.posVec(1.6F, 0F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.54F, KeyframeAnimations.posVec(1.6F, 0F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.55F, KeyframeAnimations.posVec(1.6F, 0.75F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8F, KeyframeAnimations.posVec(2.2F, 1.7F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.81F, KeyframeAnimations.posVec(1.6F, 0F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.34F, KeyframeAnimations.posVec(1.6F, 0F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.35F, KeyframeAnimations.posVec(1.6F, 0.75F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.6F, KeyframeAnimations.posVec(2.2F, 1.7F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.6F, KeyframeAnimations.posVec(1.6F, 0F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.61F, KeyframeAnimations.posVec(1.6F, 0F, 0F), AnimationChannel.Interpolations.LINEAR)
        ))
        .addAnimation("dust", new AnimationChannel(AnimationChannel.Targets.SCALE,
            new Keyframe(0F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 0.05F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.49F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 0.05F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.55F, KeyframeAnimations.scaleVec(1.2F, 1.2F, 1.2F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 0.05F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.29F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 0.05F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.35F, KeyframeAnimations.scaleVec(1.2F, 1.2F, 1.2F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.6F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 0.05F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.6F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 0.05F), AnimationChannel.Interpolations.LINEAR)
        ))
        .build();

    public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(4F).looping()
        .build();

    private FossilCleaningTableAnimation() {
    }
}
