package com.coolerpromc.ancientcreature.client.entity.animation.block;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

// Generated by art/texgen/machines/make_machines.py from art/texgen/machines/defs/fossil_identification_chamber.py - edit that, not this file.
public final class FossilIdentificationChamberAnimation {
    public static final AnimationDefinition PROCESSING = AnimationDefinition.Builder.withLength(4F).looping()
        .addAnimation("scanner_carriage", new AnimationChannel(AnimationChannel.Targets.POSITION,
            new Keyframe(0F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.9F, KeyframeAnimations.posVec(0F, -9F, 0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.1F, KeyframeAnimations.posVec(0F, -9F, 0F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.posVec(0F, 0F, 0F), AnimationChannel.Interpolations.CATMULLROM)
        ))
        .addAnimation("specimen", new AnimationChannel(AnimationChannel.Targets.ROTATION,
            new Keyframe(0F, KeyframeAnimations.degreeVec(0F, 0F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1F, KeyframeAnimations.degreeVec(0F, 90F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2F, KeyframeAnimations.degreeVec(0F, 180F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3F, KeyframeAnimations.degreeVec(0F, 270F, 0F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(4F, KeyframeAnimations.degreeVec(0F, 360F, 0F), AnimationChannel.Interpolations.LINEAR)
        ))
        .addAnimation("status_light_1", new AnimationChannel(AnimationChannel.Targets.SCALE,
            new Keyframe(0F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.49F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.99F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.49F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.5F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.99F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.49F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.5F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.99F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3.49F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3.5F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3.99F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR)
        ))
        .addAnimation("status_light_2", new AnimationChannel(AnimationChannel.Targets.SCALE,
            new Keyframe(0F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.49F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.99F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.49F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.5F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1.99F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.49F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.5F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.99F, KeyframeAnimations.scaleVec(0.05F, 0.05F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3.49F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3.5F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3.99F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.LINEAR)
        ))
        .build();

    public static final AnimationDefinition IDLE = AnimationDefinition.Builder.withLength(4F).looping()
        .addAnimation("status_light_0", new AnimationChannel(AnimationChannel.Targets.SCALE,
            new Keyframe(0F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.3333F, KeyframeAnimations.scaleVec(1.075F, 1.075F, 1F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(0.6667F, KeyframeAnimations.scaleVec(1.1299F, 1.1299F, 1F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1F, KeyframeAnimations.scaleVec(1.15F, 1.15F, 1F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.3333F, KeyframeAnimations.scaleVec(1.1299F, 1.1299F, 1F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(1.6667F, KeyframeAnimations.scaleVec(1.075F, 1.075F, 1F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.3333F, KeyframeAnimations.scaleVec(0.925F, 0.925F, 1F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(2.6667F, KeyframeAnimations.scaleVec(0.8701F, 0.8701F, 1F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3F, KeyframeAnimations.scaleVec(0.85F, 0.85F, 1F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3.3333F, KeyframeAnimations.scaleVec(0.8701F, 0.8701F, 1F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(3.6667F, KeyframeAnimations.scaleVec(0.925F, 0.925F, 1F), AnimationChannel.Interpolations.CATMULLROM),
            new Keyframe(4F, KeyframeAnimations.scaleVec(1F, 1F, 1F), AnimationChannel.Interpolations.CATMULLROM)
        ))
        .build();

    private FossilIdentificationChamberAnimation() {
    }
}
