package com.coolerpromc.ancientcreature.datagen;

import com.coolerpromc.ancientcreature.Constants;
import com.coolerpromc.ancientcreature.block.ModBlocks;
import com.coolerpromc.ancientcreature.entity.ModEntities;
import com.coolerpromc.ancientcreature.item.ModItems;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class ModLanguageProvider extends LanguageProvider {
    public ModLanguageProvider(PackOutput output) {
        super(output, Constants.MODID, "en_us");
    }

    @Override
    protected void addTranslations() {
        add("tooltip.ancientcreature.fossil_completeness", "§7Completeness: %s");
        add("tooltip.ancientcreature.genome_completeness", "§7Completeness: %s");
        add("tooltip.ancientcreature.fossil_damage_rate", "-%s%% Completeness");
        add("tooltip.ancientcreature.species", "§7Species: %s");
        add("tooltip.ancientcreature.dna_integrity_level", "§7Integrity Level: %s");

        add("jei.ancientcreature.category.fossil_hunting", "Fossil Part Hunting");
        add("jei.ancientcreature.method.chiseling", "Method: Chisel fossil ore");
        add("jei.ancientcreature.method.rock_pile", "Method: Break a rock pile that has egg");
        add("jei.ancientcreature.method.brushing", "Method: Brush suspicious blocks at dig sites");
        add("jei.ancientcreature.biomes", "Biomes: %s");
        add("jei.ancientcreature.species_result", "Possible species: %s");
        add("jei.ancientcreature.parts", "Possible parts: %s");
        add("jei.ancientcreature.parts_egg_only", "Result: Egg fossil");
        add("jei.ancientcreature.completeness_range", "Completeness: %s%%-%s%%");
        add("jei.ancientcreature.fortune_bonus", "Fortune adds 10% completeness before chisel damage");
        add("jei.ancientcreature.rock_pile_fossil_condition", "Only rock piles visibly containing a fossil yield this");
        add("jei.ancientcreature.rock_pile_egg_condition", "Only rock piles visibly containing an egg yield this");
        add("jei.ancientcreature.archaeology_chance", "Fossil chance: 5/76 (6.58%%); skulls/vertebrae unavailable");
        add("jei.ancientcreature.cleaning_preserves", "Preserves species, part, and completeness");
        add("jei.ancientcreature.dirt_output", "Also yields 0-2 dirt fragments; costs 1 brush durability");
        add("jei.ancientcreature.identification_chance", "First identification failure chance: %s%%");
        add("jei.ancientcreature.identification_damage", "On failure, completeness is reduced by %s%%");
        add("jei.ancientcreature.identification_time", "400 ticks for a new species; 100 known species");
        add("jei.ancientcreature.dna_formula", "Integrity score = completeness + fossil-part bonus");
        add("jei.ancientcreature.egg_limb_bonus", "Egg fossils use the limb bonus (0 points)");
        add("jei.ancientcreature.integrity_result", "Resulting integrity: %s");
        add("jei.ancientcreature.extraction_consumption", "Consumes fossil + vial; costs 1 fluid durability");
        add("jei.ancientcreature.genome_added", "Genome completeness added: %s%%-%s%%");
        add("jei.ancientcreature.genome_caps", "At 100%%, the cartridge becomes completed");
        add("jei.ancientcreature.same_species", "DNA Sample must have same species as filled cartridge");
        add("jei.ancientcreature.incubation_time", "Incubation time: %ss");

        add("jade.ancientcreature.remaining_time", "Remaining Time: %ss");
        add("jade.ancientcreature.hunger", "Hunger: %s/%s");
        add("jade.ancientcreature.hungry", "Hungry - will hunt");
        add("jade.ancientcreature.fed", "Fed - not hunting");
        add("config.jade.plugin_ancientcreature.egg_data", "Egg Data");
        add("config.jade.plugin_ancientcreature.creature_hunger", "Creature Hunger");

        add("tab.ancientcreature.ancient_creature", "Ancient Creature");
        add("tab.ancientcreature.fossils", "Fossils");
        add("tab.ancientcreature.chisels", "Chisels");
        add("tab.ancientcreature.machines", "Machines");
        add("tab.ancientcreature.dna_samples", "DNA Samples");
        add("tab.ancientcreature.genomes", "Genomes");
        add("tab.ancientcreature.processed_items", "Processed Items");
        add("tab.ancientcreature.fertilized_ancient_eggs", "Fertilized Eggs");
        add("tab.ancientcreature.misc", "Misc");

        add("name.ancientcreature.dirty", "Dirty");
        add("name.ancientcreature.unidentified", "Unidentified");

        add("screen.ancientcreature.field_guide", "Field Guide");
        add("guide.ancientcreature.next", "Next: %s");
        add("guide.ancientcreature.open_journal", "Open the Species Journal");
        add("guide.ancientcreature.introduction.title", "Introduction");
        add("guide.ancientcreature.introduction.1", "This guide follows the road from a buried bone to a living creature. Each chapter covers one step. Pick a chapter on the left and scroll the page with the mouse wheel. Hover over any item to see its name.");
        add("guide.ancientcreature.introduction.journey", "The Journey");
        add("guide.ancientcreature.introduction.step1", "1. Make a chisel. Fossils only drop when mined with one.");
        add("guide.ancientcreature.introduction.step2", "2. Find a fossil in Fossil Ore underground, or in rock piles on the surface.");
        add("guide.ancientcreature.introduction.step3", "3. Clean it in a Fossil Cleaning Table with a brush.");
        add("guide.ancientcreature.introduction.step4", "4. Identify it in a Fossil Identification Chamber to learn its species.");
        add("guide.ancientcreature.introduction.step5", "5. Extract its DNA in a DNA Extractor.");
        add("guide.ancientcreature.introduction.step6", "6. Sequence DNA of one species onto a Genome Cartridge until it reaches 100%%.");
        add("guide.ancientcreature.introduction.step7", "7. Grow an embryo in the Embryogenesis Chamber.");
        add("guide.ancientcreature.introduction.step8", "8. Incubate the egg, then use the Baby Creature Capsule on the ground to release your creature.");
        add("guide.ancientcreature.introduction.tip", "Better fossils make better DNA, and better DNA fills a genome in fewer samples. Teeth, skulls and egg fossils are the best finds.");
        add("guide.ancientcreature.introduction.journal", "Species Journal");
        add("guide.ancientcreature.introduction.journal.1", "Press [%s] to open the Species Journal. It lists every species identified on this world, with its habitat, diet, size, strength, incubation time and how long it takes to grow up.");
        add("guide.ancientcreature.fossils.title", "Finding Fossils");
        add("guide.ancientcreature.fossils.1", "Every fossil belongs to a species, and the species is decided by the biome where the fossil drops. The same find in a snowy plains and in a warm ocean will be different animals. If no species lives in that biome, nothing drops.");
        add("guide.ancientcreature.fossils.2", "Fresh fossils are always dirty and unidentified. Their tooltip shows ??? for the species until they are identified.");
        add("guide.ancientcreature.fossils.ore", "Fossil Ore");
        add("guide.ancientcreature.fossils.ore.1", "Single blocks of Fossil Ore generate in stone in every Overworld biome, between Y -64 and Y 50. Mine one with a chisel to get a dirty fossil of any part, including egg fossils. A pickaxe won't drop anything.");
        add("guide.ancientcreature.fossils.rock_pile", "Rock Piles");
        add("guide.ancientcreature.fossils.rock_pile.1", "Small piles of stone sit on the surface of Overworld biomes. Most are plain rocks, but some have bones or an egg poking out, so you can tell what's inside before breaking them.");
        add("guide.ancientcreature.fossils.rock_pile.2", "Break them with a chisel: plain piles give Rock Fragments, piles with bones add a dirty fossil, and piles with an egg add a dirty Egg Fossil.");
        add("guide.ancientcreature.fossils.dig_site", "Dig Sites");
        add("guide.ancientcreature.fossils.dig_site.1", "Dig sites are small excavations with suspicious sand or gravel. Brush the suspicious blocks with a brush. Brushing never damages a fossil, but only turns up claws, teeth, ribs and limbs. Dig sites are the only natural source of Egg Shell Fragments, needed for Artificial Eggs.");
        add("guide.ancientcreature.fossils.parts", "Fossil Parts");
        add("guide.ancientcreature.fossils.parts.1", "Parts differ in how much of the animal survived (completeness), how likely they are to fail a first identification, and how much they help when extracting DNA.");
        add("guide.ancientcreature.fossils.part_stats", "Identify fail: %s  DNA bonus: %s");
        add("guide.ancientcreature.fossils.tip", "Egg fossils and teeth keep the most completeness. Claws keep the least.");
        add("guide.ancientcreature.chisels.title", "Chisels");
        add("guide.ancientcreature.chisels.1", "Chisels mine Fossil Ore and rock piles. Each one chips away part of the completeness of every fossil it digs up, so a better chisel means better fossils.");
        add("guide.ancientcreature.chisels.damage", "Removes %s completeness");
        add("guide.ancientcreature.chisels.crafting", "Crafting");
        add("guide.ancientcreature.chisels.netherite", "The Netherite Chisel does no damage at all. Upgrade a Diamond Chisel at a Smithing Table.");
        add("guide.ancientcreature.chisels.2", "Chisels can be repaired in an anvil with their material. A chisel with Fortune adds 10%% completeness per level before the chisel's damage is taken off.");
        add("guide.ancientcreature.cleaning.title", "Cleaning");
        add("guide.ancientcreature.cleaning.1", "A fossil fresh out of the ground is caked in dirt. The Fossil Cleaning Table brushes it clean.");
        add("guide.ancientcreature.cleaning.2", "Put a brush in the top slot and a dirty fossil in the fossil slot.");
        add("guide.ancientcreature.cleaning.3", "Cleaning keeps the species, part and completeness exactly as they were. It never damages a fossil.");
        add("guide.ancientcreature.cleaning.4", "Each fossil costs the brush 1 durability and drops 0-2 Dirt Fragments. Four Dirt Fragments craft back into dirt.");
        add("guide.ancientcreature.identification.title", "Identification");
        add("guide.ancientcreature.identification.1", "Put a clean fossil into the Fossil Identification Chamber. It scans the fossil and reveals its species, which shows in the tooltip from then on.");
        add("guide.ancientcreature.identification.first", "The First of Its Kind");
        add("guide.ancientcreature.identification.first.1", "The first time a species is identified on a world is the hard one. Until then every scan of that species can fail, with a chance that depends on the fossil part (see Finding Fossils). A failed fossil stays unidentified and loses some completeness, but can be put back in to try again.");
        add("guide.ancientcreature.identification.first.2", "Once anyone succeeds, the species is known for everyone. Known species always identify, four times as fast, and unlock their page in the Species Journal.");
        add("guide.ancientcreature.identification.tip", "Use a tooth or a skull to unlock a new species. Once it is known, even claws identify every time.");
        add("guide.ancientcreature.dna.title", "DNA Extraction");
        add("guide.ancientcreature.dna.1", "An identified fossil still holds only scraps of DNA. The DNA Extractor pulls them into a sample. It needs Extraction Fluid, an empty Sample Vial and an identified, clean fossil.");
        add("guide.ancientcreature.dna.2", "Extraction Fluid lasts for 4 extractions. The fossil is always used up.");
        add("guide.ancientcreature.dna.supplies", "Lab Supplies");
        add("guide.ancientcreature.dna.quality", "DNA Quality");
        add("guide.ancientcreature.dna.quality.1", "A sample's integrity comes from its score: the fossil's completeness plus the fossil part's DNA bonus. Better integrity adds more to a genome.");
        add("guide.ancientcreature.dna.level", "Score %s, adds %s genome");
        add("guide.ancientcreature.dna.quality.2", "Below a score of 5%% the extraction fails: the fossil and a use of fluid are spent, but the vial is kept.");
        add("guide.ancientcreature.genome.title", "Genome Sequencing");
        add("guide.ancientcreature.genome.1", "The Genome Sequencer writes DNA onto a Genome Cartridge. Each sample adds a random share of genome depending on its integrity.");
        add("guide.ancientcreature.genome.2", "A blank cartridge takes the species of the first sample and becomes a filled cartridge.");
        add("guide.ancientcreature.genome.3", "Keep feeding samples of the same species. With a sample of another species in the slot, the sequencer just waits. At 100%% the cartridge is completed.");
        add("guide.ancientcreature.genome.4", "The cartridge stays in its slot between samples, so a hopper feeding DNA can fill it hands-free.");
        add("guide.ancientcreature.genome.tip", "Each creature needs its own completed cartridge, and the cartridge is used up when the embryo is made.");
        add("guide.ancientcreature.embryogenesis.title", "Embryogenesis");
        add("guide.ancientcreature.embryogenesis.1", "The Embryogenesis Chamber combines a completed genome with an Artificial Egg and Nutrient Solution to make a fertilized egg of that species.");
        add("guide.ancientcreature.embryogenesis.2", "All three inputs are used up, including the cartridge.");
        add("guide.ancientcreature.embryogenesis.supplies", "Eggs and Nutrients");
        add("guide.ancientcreature.embryogenesis.3", "Egg Shell Fragments come from brushing suspicious sand and gravel at dig sites. Nutrient Solution uses Water Bottles and bone meal, and one craft makes 4.");
        add("guide.ancientcreature.incubation.title", "Incubation");
        add("guide.ancientcreature.incubation.1", "The Incubator keeps a fertilized egg warm until it is ready to hatch.");
        add("guide.ancientcreature.incubation.2", "How long it takes depends on the species: bigger creatures take longer. The Species Journal lists each species' incubation time.");
        add("guide.ancientcreature.incubation.release", "Releasing Your Creature");
        add("guide.ancientcreature.incubation.release.1", "Use the Baby Creature Capsule on a block to release a baby of its species. You become its owner. It grows into an adult over time, and once grown you can ride it.");
        add("guide.ancientcreature.incubation.release.2", "Capsules can't be used on Peaceful difficulty.");
        add("guide.ancientcreature.creatures.title", "Your Creatures");
        add("guide.ancientcreature.creatures.1", "Every species has its own size, strength, diet and temperament. Creatures you release from a capsule or hatch from a bred egg belong to you.");
        add("guide.ancientcreature.creatures.hunger", "Hunger");
        add("guide.ancientcreature.creatures.hunger.1", "Every creature has a hunger meter that slowly drains. Predators only go hunting once they are hungry and stop once they have eaten, so a well-fed predator won't chase everything in sight.");
        add("guide.ancientcreature.creatures.hunger.2", "Hand-feed a creature one of its diet items to fill its hunger. Hungry or not, creatures always defend themselves when attacked.");
        add("guide.ancientcreature.creatures.breeding", "Breeding");
        add("guide.ancientcreature.creatures.breeding.1", "Feed two adults of the same species their diet items to breed them. They lay an egg on the spot, which hatches after the species' incubation time into a baby owned by the nearest player within 10 blocks. Creatures with no diet can't be bred.");
        add("guide.ancientcreature.creatures.riding", "Riding");
        add("guide.ancientcreature.creatures.riding.1", "The owner can ride an adult creature with an empty hand or a non-food item: right-click it. No saddle is needed. Babies can't be ridden, and only one rider fits at a time.");
        add("guide.ancientcreature.creatures.riding.2", "Steer with the movement keys and the mouse. Flying and swimming creatures follow where you look: look up to climb and down to dive. Jump gains extra height while flying, and sneak dismounts.");
        add("guide.ancientcreature.creatures.riding.3", "Right-clicking with food feeds or breeds the creature instead, and sneak-right-click never mounts.");
        add("guide.ancientcreature.creatures.tip", "Wild creatures and your own behave the same otherwise, so keep predators away from your farm animals.");
        add("guide.ancientcreature.automation.title", "Automation");
        add("guide.ancientcreature.automation.1", "Every machine works with hoppers and pipes. Each side of a machine feeds a different slot. Every machine except the Fossil Cleaning Table is two blocks tall, so leave a free block above it.");
        add("guide.ancientcreature.automation.cleaning", "Top: brush. Sides: dirty fossil. Bottom: clean fossil and dirt fragments.");
        add("guide.ancientcreature.automation.identification", "Top and sides: fossil. Bottom: result.");
        add("guide.ancientcreature.automation.dna", "Top: Sample Vial. North/south: Extraction Fluid. East/west: fossil. Bottom: DNA sample.");
        add("guide.ancientcreature.automation.genome", "Top: cartridge. Sides: DNA sample. Bottom: cartridge.");
        add("guide.ancientcreature.automation.embryogenesis", "Top: Artificial Egg. North/south: Nutrient Solution. East/west: completed cartridge. Bottom: fertilized egg.");
        add("guide.ancientcreature.automation.incubation", "Top and sides: fertilized egg. Bottom: capsule.");
        add("guide.ancientcreature.automation.tip", "Chain machines with hoppers: each machine's bottom output can feed the next machine's input side.");

        add("key.ancientcreature.open_species_journal", "Open Species Journal");
        add("key.category.ancientcreature.ancient_creature", "Ancient Creature");
        add("screen.ancientcreature.species_journal", "Species Journal");
        add("screen.ancientcreature.species_journal.search", "Search species...");
        add("screen.ancientcreature.species_journal.progress", "%s / %s identified");
        add("screen.ancientcreature.species_journal.no_results", "No entries found");
        add("screen.ancientcreature.species_journal.classified", "Identify a fossil to unlock");
        add("screen.ancientcreature.species_journal.category.land", "Land species");
        add("screen.ancientcreature.species_journal.category.aquatic", "Aquatic species");
        add("screen.ancientcreature.species_journal.category.flying", "Flying species");
        add("screen.ancientcreature.species_journal.size", "Size");
        add("screen.ancientcreature.species_journal.health", "Health");
        add("screen.ancientcreature.species_journal.diet", "Diet");
        add("screen.ancientcreature.species_journal.attack", "Attack");
        add("screen.ancientcreature.species_journal.habitat", "Habitat");
        add("screen.ancientcreature.species_journal.speed", "Speed");
        add("screen.ancientcreature.species_journal.maturity", "Maturity");
        add("screen.ancientcreature.species_journal.incubation", "Incubation");

        add("fossilPart.ancientcreature.empty", "Illegal Item");
        add("fossilPart.ancientcreature.rib", "Rib Fossil Fragment");
        add("fossilPart.ancientcreature.tooth", "Tooth Fossil Fragment");
        add("fossilPart.ancientcreature.skull", "Skull Fossil Fragment");
        add("fossilPart.ancientcreature.vertebra", "Vertebra Fossil Fragment");
        add("fossilPart.ancientcreature.limb", "Limb Fossil Fragment");
        add("fossilPart.ancientcreature.claw", "Claw Fossil Fragment");
        add("fossilPart.ancientcreature.egg", "Egg Fossil");

        add("species.ancientcreature.triceratops", "Triceratops");
        add("species.ancientcreature.tyrannosaurus_rex", "Tyrannosaurus Rex");
        add("species.ancientcreature.megalodon", "Megalodon");
        add("species.ancientcreature.pteranodon", "Pteranodon");
        add("species.ancientcreature.ankylosaurus", "Ankylosaurus");
        add("species.ancientcreature.deinonychus", "Deinonychus");
        add("species.ancientcreature.brachiosaurus", "Brachiosaurus");
        add("species.ancientcreature.argentinosaurus", "Argentinosaurus");
        add("species.ancientcreature.arthropleura", "Arthropleura");
        add("species.ancientcreature.carnotaurus", "Carnotaurus");
        add("species.ancientcreature.dilophosaurus", "Dilophosaurus");
        add("species.ancientcreature.dire_wolf", "Dire Wolf");
        add("species.ancientcreature.dunkleosteus", "Dunkleosteus");
        add("species.ancientcreature.mosasaurus", "Mosasaurus");
        add("species.ancientcreature.parasaurolophus", "Parasaurolophus");
        add("species.ancientcreature.plesiosaurus", "Plesiosaurus");
        add("species.ancientcreature.quetzalcoatlus", "Quetzalcoatlus");
        add("species.ancientcreature.smilodon", "Smilodon");
        add("species.ancientcreature.spinosaurus", "Spinosaurus");
        add("species.ancientcreature.stegosaurus", "Stegosaurus");
        add("species.ancientcreature.velociraptor", "Velociraptor");
        add("species.ancientcreature.woolly_mammoth", "Woolly Mammoth");
        add("species.ancientcreature.woolly_rhinoceros", "Woolly Rhinoceros");
        add("species.ancientcreature.unidentified", "???");

        add("dna.ancientcreature.degraded", "Degraded");
        add("dna.ancientcreature.partial", "Partial");
        add("dna.ancientcreature.stable", "Stable");
        add("dna.ancientcreature.preserved_embryo", "Preserved Embryo");

        add("subtitles.ancientcreature.block.fossil_identification_chamber.scan", "Fossil chamber scans");
        add("subtitles.ancientcreature.block.fossil_identification_chamber.failed", "Fossil identification fails");
        add("subtitles.ancientcreature.block.fossil_cleaning_table.brush", "Brush scrapes fossil");
        add("subtitles.ancientcreature.block.dna_extractor.processing", "DNA extractor processes sample");
        add("subtitles.ancientcreature.block.genome_sequencer.processing", "Genome sequencer analyzes sample");
        add("subtitles.ancientcreature.block.embryogenesis_chamber.processing", "Embryogenesis chamber cultivates embryo");
        add("subtitles.ancientcreature.block.incubator.processing", "Incubator regulates temperature");
        add("subtitles.ancientcreature.entity.triceratops.ambient", "Triceratops rumbles");
        add("subtitles.ancientcreature.entity.triceratops.bellow", "Triceratops bellows");
        add("subtitles.ancientcreature.entity.triceratops.hurt", "Triceratops hurts");
        add("subtitles.ancientcreature.entity.triceratops.death", "Triceratops dies");
        add("subtitles.ancientcreature.entity.triceratops.attack", "Triceratops attacks");
        add("subtitles.ancientcreature.entity.triceratops.step", "Triceratops steps");
        add("subtitles.ancientcreature.entity.tyrannosaurus_rex.ambient", "Tyrannosaurus rex rumbles");
        add("subtitles.ancientcreature.entity.tyrannosaurus_rex.roar", "Tyrannosaurus rex roars");
        add("subtitles.ancientcreature.entity.tyrannosaurus_rex.hurt", "Tyrannosaurus rex hurts");
        add("subtitles.ancientcreature.entity.tyrannosaurus_rex.death", "Tyrannosaurus rex dies");
        add("subtitles.ancientcreature.entity.tyrannosaurus_rex.bite", "Tyrannosaurus rex bites");
        add("subtitles.ancientcreature.entity.tyrannosaurus_rex.step", "Tyrannosaurus rex steps");
        add("subtitles.ancientcreature.entity.megalodon.ambient", "Megalodon looms");
        add("subtitles.ancientcreature.entity.megalodon.hurt", "Megalodon hurts");
        add("subtitles.ancientcreature.entity.megalodon.death", "Megalodon dies");
        add("subtitles.ancientcreature.entity.megalodon.bite", "Megalodon bites");
        add("subtitles.ancientcreature.entity.megalodon.step", "Megalodon thrashes");
        add("subtitles.ancientcreature.entity.pteranodon.ambient", "Pteranodon croaks");
        add("subtitles.ancientcreature.entity.pteranodon.alert", "Pteranodon screeches");
        add("subtitles.ancientcreature.entity.pteranodon.hurt", "Pteranodon hurts");
        add("subtitles.ancientcreature.entity.pteranodon.death", "Pteranodon dies");
        add("subtitles.ancientcreature.entity.pteranodon.attack", "Pteranodon snaps its beak");
        add("subtitles.ancientcreature.entity.pteranodon.step", "Pteranodon steps");
        add("subtitles.ancientcreature.entity.ankylosaurus.ambient", "Ankylosaurus rumbles");
        add("subtitles.ancientcreature.entity.ankylosaurus.alert", "Ankylosaurus bellows");
        add("subtitles.ancientcreature.entity.ankylosaurus.hurt", "Ankylosaurus hurts");
        add("subtitles.ancientcreature.entity.ankylosaurus.death", "Ankylosaurus dies");
        add("subtitles.ancientcreature.entity.ankylosaurus.attack", "Ankylosaurus swings its tail club");
        add("subtitles.ancientcreature.entity.ankylosaurus.step", "Ankylosaurus stomps");
        add("subtitles.ancientcreature.entity.deinonychus.ambient", "Deinonychus chirps");
        add("subtitles.ancientcreature.entity.deinonychus.call", "Deinonychus calls to its pack");
        add("subtitles.ancientcreature.entity.deinonychus.hurt", "Deinonychus hurts");
        add("subtitles.ancientcreature.entity.deinonychus.death", "Deinonychus dies");
        add("subtitles.ancientcreature.entity.deinonychus.attack", "Deinonychus snaps");
        add("subtitles.ancientcreature.entity.deinonychus.step", "Deinonychus steps");
        add("subtitles.ancientcreature.entity.brachiosaurus.ambient", "Brachiosaurus rumbles");
        add("subtitles.ancientcreature.entity.brachiosaurus.call", "Brachiosaurus calls across the canopy");
        add("subtitles.ancientcreature.entity.brachiosaurus.hurt", "Brachiosaurus hurts");
        add("subtitles.ancientcreature.entity.brachiosaurus.death", "Brachiosaurus dies");
        add("subtitles.ancientcreature.entity.brachiosaurus.attack", "Brachiosaurus sweeps its tail");
        add("subtitles.ancientcreature.entity.brachiosaurus.step", "Brachiosaurus stomps");
        add("subtitles.ancientcreature.entity.argentinosaurus.ambient", "Argentinosaurus rumbles");
        add("subtitles.ancientcreature.entity.argentinosaurus.alert", "Argentinosaurus bellows");
        add("subtitles.ancientcreature.entity.argentinosaurus.hurt", "Argentinosaurus hurts");
        add("subtitles.ancientcreature.entity.argentinosaurus.death", "Argentinosaurus dies");
        add("subtitles.ancientcreature.entity.argentinosaurus.attack", "Argentinosaurus sweeps its tail");
        add("subtitles.ancientcreature.entity.argentinosaurus.step", "Argentinosaurus stomps");
        add("subtitles.ancientcreature.entity.arthropleura.ambient", "Arthropleura clicks");
        add("subtitles.ancientcreature.entity.arthropleura.alert", "Arthropleura hisses");
        add("subtitles.ancientcreature.entity.arthropleura.hurt", "Arthropleura hurts");
        add("subtitles.ancientcreature.entity.arthropleura.death", "Arthropleura dies");
        add("subtitles.ancientcreature.entity.arthropleura.attack", "Arthropleura bites");
        add("subtitles.ancientcreature.entity.arthropleura.step", "Arthropleura skitters");
        add("subtitles.ancientcreature.entity.carnotaurus.ambient", "Carnotaurus growls");
        add("subtitles.ancientcreature.entity.carnotaurus.alert", "Carnotaurus roars");
        add("subtitles.ancientcreature.entity.carnotaurus.hurt", "Carnotaurus hurts");
        add("subtitles.ancientcreature.entity.carnotaurus.death", "Carnotaurus dies");
        add("subtitles.ancientcreature.entity.carnotaurus.attack", "Carnotaurus bites");
        add("subtitles.ancientcreature.entity.carnotaurus.step", "Carnotaurus steps");
        add("subtitles.ancientcreature.entity.dilophosaurus.ambient", "Dilophosaurus chirps");
        add("subtitles.ancientcreature.entity.dilophosaurus.alert", "Dilophosaurus rattles its frill");
        add("subtitles.ancientcreature.entity.dilophosaurus.hurt", "Dilophosaurus hurts");
        add("subtitles.ancientcreature.entity.dilophosaurus.death", "Dilophosaurus dies");
        add("subtitles.ancientcreature.entity.dilophosaurus.attack", "Dilophosaurus spits");
        add("subtitles.ancientcreature.entity.dilophosaurus.step", "Dilophosaurus steps");
        add("subtitles.ancientcreature.entity.dire_wolf.ambient", "Dire wolf growls");
        add("subtitles.ancientcreature.entity.dire_wolf.alert", "Dire wolf howls");
        add("subtitles.ancientcreature.entity.dire_wolf.hurt", "Dire wolf hurts");
        add("subtitles.ancientcreature.entity.dire_wolf.death", "Dire wolf dies");
        add("subtitles.ancientcreature.entity.dire_wolf.attack", "Dire wolf bites");
        add("subtitles.ancientcreature.entity.dire_wolf.step", "Dire wolf pads");
        add("subtitles.ancientcreature.entity.dunkleosteus.ambient", "Dunkleosteus looms");
        add("subtitles.ancientcreature.entity.dunkleosteus.alert", "Dunkleosteus snaps its jaws");
        add("subtitles.ancientcreature.entity.dunkleosteus.hurt", "Dunkleosteus hurts");
        add("subtitles.ancientcreature.entity.dunkleosteus.death", "Dunkleosteus dies");
        add("subtitles.ancientcreature.entity.dunkleosteus.attack", "Dunkleosteus bites");
        add("subtitles.ancientcreature.entity.dunkleosteus.step", "Dunkleosteus thrashes");
        add("subtitles.ancientcreature.entity.mosasaurus.ambient", "Mosasaurus looms");
        add("subtitles.ancientcreature.entity.mosasaurus.alert", "Mosasaurus roars");
        add("subtitles.ancientcreature.entity.mosasaurus.hurt", "Mosasaurus hurts");
        add("subtitles.ancientcreature.entity.mosasaurus.death", "Mosasaurus dies");
        add("subtitles.ancientcreature.entity.mosasaurus.attack", "Mosasaurus bites");
        add("subtitles.ancientcreature.entity.mosasaurus.step", "Mosasaurus thrashes");
        add("subtitles.ancientcreature.entity.parasaurolophus.ambient", "Parasaurolophus hums");
        add("subtitles.ancientcreature.entity.parasaurolophus.alert", "Parasaurolophus trumpets");
        add("subtitles.ancientcreature.entity.parasaurolophus.hurt", "Parasaurolophus hurts");
        add("subtitles.ancientcreature.entity.parasaurolophus.death", "Parasaurolophus dies");
        add("subtitles.ancientcreature.entity.parasaurolophus.attack", "Parasaurolophus kicks");
        add("subtitles.ancientcreature.entity.parasaurolophus.step", "Parasaurolophus steps");
        add("subtitles.ancientcreature.entity.plesiosaurus.ambient", "Plesiosaurus calls");
        add("subtitles.ancientcreature.entity.plesiosaurus.alert", "Plesiosaurus bellows");
        add("subtitles.ancientcreature.entity.plesiosaurus.hurt", "Plesiosaurus hurts");
        add("subtitles.ancientcreature.entity.plesiosaurus.death", "Plesiosaurus dies");
        add("subtitles.ancientcreature.entity.plesiosaurus.attack", "Plesiosaurus bites");
        add("subtitles.ancientcreature.entity.plesiosaurus.step", "Plesiosaurus paddles");
        add("subtitles.ancientcreature.entity.quetzalcoatlus.ambient", "Quetzalcoatlus croaks");
        add("subtitles.ancientcreature.entity.quetzalcoatlus.alert", "Quetzalcoatlus screeches");
        add("subtitles.ancientcreature.entity.quetzalcoatlus.hurt", "Quetzalcoatlus hurts");
        add("subtitles.ancientcreature.entity.quetzalcoatlus.death", "Quetzalcoatlus dies");
        add("subtitles.ancientcreature.entity.quetzalcoatlus.attack", "Quetzalcoatlus snaps its beak");
        add("subtitles.ancientcreature.entity.quetzalcoatlus.step", "Quetzalcoatlus steps");
        add("subtitles.ancientcreature.entity.smilodon.ambient", "Smilodon growls");
        add("subtitles.ancientcreature.entity.smilodon.alert", "Smilodon snarls");
        add("subtitles.ancientcreature.entity.smilodon.hurt", "Smilodon hurts");
        add("subtitles.ancientcreature.entity.smilodon.death", "Smilodon dies");
        add("subtitles.ancientcreature.entity.smilodon.attack", "Smilodon bites");
        add("subtitles.ancientcreature.entity.smilodon.step", "Smilodon pads");
        add("subtitles.ancientcreature.entity.spinosaurus.ambient", "Spinosaurus rumbles");
        add("subtitles.ancientcreature.entity.spinosaurus.alert", "Spinosaurus roars");
        add("subtitles.ancientcreature.entity.spinosaurus.hurt", "Spinosaurus hurts");
        add("subtitles.ancientcreature.entity.spinosaurus.death", "Spinosaurus dies");
        add("subtitles.ancientcreature.entity.spinosaurus.attack", "Spinosaurus bites");
        add("subtitles.ancientcreature.entity.spinosaurus.step", "Spinosaurus stomps");
        add("subtitles.ancientcreature.entity.stegosaurus.ambient", "Stegosaurus rumbles");
        add("subtitles.ancientcreature.entity.stegosaurus.alert", "Stegosaurus bellows");
        add("subtitles.ancientcreature.entity.stegosaurus.hurt", "Stegosaurus hurts");
        add("subtitles.ancientcreature.entity.stegosaurus.death", "Stegosaurus dies");
        add("subtitles.ancientcreature.entity.stegosaurus.attack", "Stegosaurus swings its tail spikes");
        add("subtitles.ancientcreature.entity.stegosaurus.step", "Stegosaurus stomps");
        add("subtitles.ancientcreature.entity.velociraptor.ambient", "Velociraptor chirps");
        add("subtitles.ancientcreature.entity.velociraptor.alert", "Velociraptor screeches");
        add("subtitles.ancientcreature.entity.velociraptor.hurt", "Velociraptor hurts");
        add("subtitles.ancientcreature.entity.velociraptor.death", "Velociraptor dies");
        add("subtitles.ancientcreature.entity.velociraptor.attack", "Velociraptor slashes");
        add("subtitles.ancientcreature.entity.velociraptor.step", "Velociraptor steps");
        add("subtitles.ancientcreature.entity.woolly_mammoth.ambient", "Woolly mammoth rumbles");
        add("subtitles.ancientcreature.entity.woolly_mammoth.alert", "Woolly mammoth trumpets");
        add("subtitles.ancientcreature.entity.woolly_mammoth.hurt", "Woolly mammoth hurts");
        add("subtitles.ancientcreature.entity.woolly_mammoth.death", "Woolly mammoth dies");
        add("subtitles.ancientcreature.entity.woolly_mammoth.attack", "Woolly mammoth charges");
        add("subtitles.ancientcreature.entity.woolly_mammoth.step", "Woolly mammoth stomps");
        add("subtitles.ancientcreature.entity.woolly_rhinoceros.ambient", "Woolly rhinoceros snorts");
        add("subtitles.ancientcreature.entity.woolly_rhinoceros.alert", "Woolly rhinoceros bellows");
        add("subtitles.ancientcreature.entity.woolly_rhinoceros.hurt", "Woolly rhinoceros hurts");
        add("subtitles.ancientcreature.entity.woolly_rhinoceros.death", "Woolly rhinoceros dies");
        add("subtitles.ancientcreature.entity.woolly_rhinoceros.attack", "Woolly rhinoceros charges");
        add("subtitles.ancientcreature.entity.woolly_rhinoceros.step", "Woolly rhinoceros stomps");

        add("advancements.ancientcreature.progression.root.title", "Ancient Creature");
        add("advancements.ancientcreature.progression.root.description", "Unearth the past and bring ancient creatures back to life");
        add("advancements.ancientcreature.progression.craft_chisel.title", "The Paleontologist");
        add("advancements.ancientcreature.progression.craft_chisel.description", "Obtain a chisel for extracting delicate fossils");
        add("advancements.ancientcreature.progression.obtain_fossil.title", "A Piece of the Past");
        add("advancements.ancientcreature.progression.obtain_fossil.description", "Obtain a fossil fragment or an egg fossil");
        add("advancements.ancientcreature.progression.craft_cleaning_table.title", "Dusting Off History");
        add("advancements.ancientcreature.progression.craft_cleaning_table.description", "Craft a Fossil Cleaning Table");
        add("advancements.ancientcreature.progression.craft_identification_chamber.title", "Know Your Fossil");
        add("advancements.ancientcreature.progression.craft_identification_chamber.description", "Craft a Fossil Identification Chamber");
        add("advancements.ancientcreature.progression.craft_dna_extractor.title", "Molecular Archaeology");
        add("advancements.ancientcreature.progression.craft_dna_extractor.description", "Craft a DNA Extractor");
        add("advancements.ancientcreature.progression.extract_dna.title", "Ancient Code");
        add("advancements.ancientcreature.progression.extract_dna.description", "Extract a DNA sample from an identified fossil");
        add("advancements.ancientcreature.progression.craft_genome_sequencer.title", "Reading the Blueprint");
        add("advancements.ancientcreature.progression.craft_genome_sequencer.description", "Craft a Genome Sequencer");
        add("advancements.ancientcreature.progression.complete_genome.title", "Genome Complete");
        add("advancements.ancientcreature.progression.complete_genome.description", "Complete an ancient creature's genome cartridge");
        add("advancements.ancientcreature.progression.craft_embryogenesis_chamber.title", "Building Life");
        add("advancements.ancientcreature.progression.craft_embryogenesis_chamber.description", "Craft an Embryogenesis Chamber");
        add("advancements.ancientcreature.progression.create_fertilized_egg.title", "A Spark of Life");
        add("advancements.ancientcreature.progression.create_fertilized_egg.description", "Create a fertilized ancient egg");
        add("advancements.ancientcreature.progression.craft_incubator.title", "Handle With Care");
        add("advancements.ancientcreature.progression.craft_incubator.description", "Craft an Incubator for your ancient egg");
        add("advancements.ancientcreature.progression.revive_creature.title", "Life Finds a Way");
        add("advancements.ancientcreature.progression.revive_creature.description", "Incubate a baby ancient creature and bring it back from extinction");

        // The generic entity's name is only seen in /summon output and death messages; a data-driven
        // creature is normally named after its species.
        add(ModEntities.ANCIENT_CREATURE.get(), "Ancient Creature");

        add(ModItems.FIELD_GUIDE.get(), "Paleontologist's Field Guide");
        add(ModItems.STONE_CHISEL.get(), "Stone Chisel");
        add(ModItems.COPPER_CHISEL.get(), "Copper Chisel");
        add(ModItems.IRON_CHISEL.get(), "Iron Chisel");
        add(ModItems.GOLDEN_CHISEL.get(), "Golden Chisel");
        add(ModItems.DIAMOND_CHISEL.get(), "Diamond Chisel");
        add(ModItems.NETHERITE_CHISEL.get(), "Netherite Chisel");

        add(ModItems.FOSSIL_PART.get(), "Fossil Fragment");
        add(ModItems.EGG_SHELL_FRAGMENT.get(), "Egg Shell Fragment");
        add(ModItems.ROCK_FRAGMENT.get(), "Rock Fragment");
        add(ModItems.DIRT_FRAGMENT.get(), "Dirt Fragment");
        add(ModItems.DNA_SAMPLE.get(), "DNA Sample");
        add(ModItems.EXTRACTION_FLUID.get(), "Extraction Fluid");
        add(ModItems.SAMPLE_VIAL.get(), "Sample Vial");
        add(ModItems.GENOME_CARTRIDGE_BLANK.get(), "Genome Cartridge (Blank)");
        add(ModItems.GENOME_CARTRIDGE_FILLED.get(), "Genome Cartridge (Filled)");
        add(ModItems.GENOME_CARTRIDGE_COMPLETED.get(), "Genome Cartridge (Completed)");
        add(ModItems.ARTIFICIAL_EGG.get(), "Artificial Egg");
        add(ModItems.NUTRIENT_SOLUTION.get(), "Nutrient Solution");
        add(ModItems.FERTILIZED_ANCIENT_EGG.get(), "Fertilized Ancient Egg");
        add(ModItems.BABY_CREATURE_CAPSULE.get(), "Baby Creature Capsule");

        add(ModBlocks.FOSSIL_ORE.getBlock(), "Fossil Ore");
        add(ModBlocks.ROCK_PILE.getBlock(), "Rock Pile");
        add(ModBlocks.FOSSIL_CLEANING_TABLE.getBlock(), "Fossil Cleaning Table");
        add(ModBlocks.FOSSIL_IDENTIFICATION_CHAMBER.getBlock(), "Fossil Identification Chamber");
        add(ModBlocks.DNA_EXTRACTOR.getBlock(), "DNA Extractor");
        add(ModBlocks.GENOME_SEQUENCER.getBlock(), "Genome Sequencer");
        add(ModBlocks.EMBRYOGENESIS_CHAMBER.getBlock(), "Embryogenesis Chamber");
        add(ModBlocks.INCUBATOR.getBlock(), "Incubator");
        add(ModBlocks.EGG.getBlock(), "Egg");
    }
}
