package com.coolerpromc.ancientcreature.client.entity.model.block;

import com.coolerpromc.ancientcreature.client.entity.animation.block.DNAExtractorAnimation;
import com.coolerpromc.ancientcreature.client.entity.state.block.DNAExtractorRenderState;
import net.minecraft.client.animation.KeyframeAnimation;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

// Generated by art/texgen/machines/make_machines.py from art/texgen/machines/defs/dna_extractor.py - edit that, not this file.
public class DNAExtractorModel extends EntityModel<DNAExtractorRenderState> {
    private final KeyframeAnimation processingAnimation;
    private final KeyframeAnimation idleAnimation;

    public DNAExtractorModel(ModelPart root) {
        super(root);
        this.processingAnimation = DNAExtractorAnimation.PROCESSING.bake(root);
        this.idleAnimation = DNAExtractorAnimation.IDLE.bake(root);
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();

        PartDefinition dnaExtractor = partdefinition.addOrReplaceChild("dna_extractor", CubeListBuilder.create(), PartPose.offset(0.0F, 0.0F, 0.0F));

        dnaExtractor.addOrReplaceChild("housing", CubeListBuilder.create()
            .texOffs(136, 94).addBox(-7.6F, 23.4F, -7.6F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(136, 94).addBox(-7.6F, 23.4F, 5.9F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(136, 94).addBox(5.9F, 23.4F, -7.6F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(136, 94).addBox(5.9F, 23.4F, 5.9F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(0, 48).addBox(-8.0F, 21.8F, -7.7F, 16.0F, 1.6F, 15.7F, new CubeDeformation(0.0F))
            .texOffs(0, 0).addBox(-7.75F, 14.5F, -7.2F, 15.5F, 7.3F, 15.2F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(86, 24).addBox(-7.45F, 14.85F, -7.6F, 7.1F, 6.6F, 0.45F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(16, 100).addBox(-5.65F, 15.95F, -8.05F, 3.5F, 0.5F, 0.5F, new CubeDeformation(0.0F))
            .texOffs(102, 24).addBox(0.35F, 14.85F, -7.6F, 7.1F, 6.6F, 0.45F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(26, 100).addBox(2.15F, 15.95F, -8.05F, 3.5F, 0.5F, 0.5F, new CubeDeformation(0.0F))
            .texOffs(65, 48).addBox(-8.0F, 13.5F, -8.0F, 16.0F, 1.0F, 16.0F, new CubeDeformation(0.0F))
            .texOffs(131, 48).addBox(-8.0F, 2.5F, 4.6F, 16.0F, 11.0F, 3.4F, new CubeDeformation(0.0F))
            .texOffs(60, 68).addBox(-8.0F, 2.5F, -8.0F, 1.4F, 11.0F, 1.6F, new CubeDeformation(0.0F))
            .texOffs(68, 68).addBox(6.6F, 2.5F, -8.0F, 1.4F, 11.0F, 1.6F, new CubeDeformation(0.0F))
            .texOffs(62, 0).addBox(-8.0F, 0.0F, -8.0F, 16.0F, 2.5F, 16.0F, new CubeDeformation(0.0F), 0.5F, 0.5F), PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition chamber = dnaExtractor.addOrReplaceChild("chamber", CubeListBuilder.create()
            .texOffs(0, 84).addBox(-5.1F, -3.0F, -1.9125F, 10.2F, 3.5F, 4.225F, new CubeDeformation(0.0F))
            .texOffs(0, 68).addBox(-2.1125F, -3.012F, -4.9F, 4.225F, 3.524F, 10.2F, new CubeDeformation(0.0F))
            .texOffs(16, 94).addBox(-4.4F, -3.15F, -1.6225F, 8.8F, 0.25F, 3.6451F, new CubeDeformation(0.0F))
            .texOffs(136, 68).addBox(-1.8225F, -3.162F, -4.2F, 3.6451F, 0.274F, 8.8F, new CubeDeformation(0.0F))
            .texOffs(184, 84).addBox(-2.1314F, -7.15F, -4.75F, 4.2627F, 4.0F, 0.18F, new CubeDeformation(0.0F))
            .texOffs(194, 84).addBox(-2.1314F, -7.15F, 4.97F, 4.2627F, 4.0F, 0.18F, new CubeDeformation(0.0F))
            .texOffs(98, 84).addBox(-5.1F, -7.7F, -1.9125F, 10.2F, 0.55F, 4.225F, new CubeDeformation(0.0F))
            .texOffs(76, 68).addBox(-2.1125F, -7.712F, -4.9F, 4.225F, 0.574F, 10.2F, new CubeDeformation(0.0F))
            .texOffs(99, 94).addBox(-2.1F, -8.15F, -0.6698F, 4.2F, 0.45F, 1.7397F, new CubeDeformation(0.0F))
            .texOffs(158, 84).addBox(-0.8698F, -8.162F, -1.9F, 1.7397F, 0.474F, 4.2F, new CubeDeformation(0.0F))
            .texOffs(192, 94).addBox(-1.3F, -8.65F, -0.1F, 2.6F, 0.5F, 0.6F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 13.0F, 0.0F));

        chamber.addOrReplaceChild("bowl_r1", CubeListBuilder.create()
            .texOffs(30, 84).addBox(-5.1F, -3.524F, -2.1125F, 10.2F, 3.548F, 4.225F, new CubeDeformation(0.0F))
            .texOffs(30, 68).addBox(-2.1125F, -3.536F, -5.1F, 4.225F, 3.572F, 10.2F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.5F, 0.2F, 0.0F, 0.7854F, 0.0F));

        chamber.addOrReplaceChild("bowl_floor_r1", CubeListBuilder.create()
            .texOffs(42, 94).addBox(-4.4F, -0.274F, -1.8225F, 8.8F, 0.298F, 3.6451F, new CubeDeformation(0.0F))
            .texOffs(162, 68).addBox(-1.8225F, -0.286F, -4.4F, 3.6451F, 0.322F, 8.8F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -2.9F, 0.2F, 0.0F, 0.7854F, 0.0F));

        chamber.addOrReplaceChild("dome_1", CubeListBuilder.create()
            .texOffs(204, 84).addBox(-2.1314F, -4.0F, -4.95F, 4.2627F, 4.0F, 0.18F, new CubeDeformation(0.0F))
            .texOffs(214, 84).addBox(-2.1314F, -4.0F, 4.77F, 4.2627F, 4.0F, 0.18F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -3.15F, 0.2F, 0.0F, 0.7854F, 0.0F));

        chamber.addOrReplaceChild("dome_2", CubeListBuilder.create()
            .texOffs(224, 84).addBox(-2.1314F, -4.0F, -4.95F, 4.2627F, 4.0F, 0.18F, new CubeDeformation(0.0F))
            .texOffs(234, 84).addBox(-2.1314F, -4.0F, 4.77F, 4.2627F, 4.0F, 0.18F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -3.15F, 0.2F, 0.0F, 1.5708F, 0.0F));

        chamber.addOrReplaceChild("dome_3", CubeListBuilder.create()
            .texOffs(244, 84).addBox(-2.1314F, -4.0F, -4.95F, 4.2627F, 4.0F, 0.18F, new CubeDeformation(0.0F))
            .texOffs(0, 94).addBox(-2.1314F, -4.0F, 4.77F, 4.2627F, 4.0F, 0.18F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -3.15F, 0.2F, 0.0F, 2.3562F, 0.0F));

        chamber.addOrReplaceChild("lid_r1", CubeListBuilder.create()
            .texOffs(128, 84).addBox(-5.1F, -0.574F, -2.1125F, 10.2F, 0.598F, 4.225F, new CubeDeformation(0.0F))
            .texOffs(106, 68).addBox(-2.1125F, -0.586F, -5.1F, 4.225F, 0.622F, 10.2F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -7.15F, 0.2F, 0.0F, 0.7854F, 0.0F));

        chamber.addOrReplaceChild("lid_cap_r1", CubeListBuilder.create()
            .texOffs(112, 94).addBox(-2.1F, -0.474F, -0.8698F, 4.2F, 0.498F, 1.7397F, new CubeDeformation(0.0F))
            .texOffs(171, 84).addBox(-0.8698F, -0.486F, -2.1F, 1.7397F, 0.522F, 4.2F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -7.7F, 0.2F, 0.0F, 0.7854F, 0.0F));

        PartDefinition rotor = chamber.addOrReplaceChild("rotor", CubeListBuilder.create()
            .texOffs(144, 94).addBox(-1.0F, -1.05F, -0.4142F, 2.0F, 1.9F, 0.8284F, new CubeDeformation(0.0F))
            .texOffs(75, 94).addBox(-0.4142F, -1.062F, -1.0F, 0.8284F, 1.924F, 2.0F, new CubeDeformation(0.0F))
            .texOffs(232, 94).addBox(-0.4F, -1.55F, -0.4F, 0.8F, 0.5F, 0.8F, new CubeDeformation(0.0F))
            .texOffs(176, 94).addBox(-3.2F, -0.8F, -0.45F, 6.4F, 0.45F, 0.9F, new CubeDeformation(0.0F))
            .texOffs(60, 84).addBox(-0.45F, -0.78F, -3.2F, 0.9F, 0.45F, 6.4F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -4.0F, 0.2F));

        rotor.addOrReplaceChild("hub_r1", CubeListBuilder.create()
            .texOffs(151, 94).addBox(-1.0F, -1.924F, -0.4142F, 2.0F, 1.948F, 0.8284F, new CubeDeformation(0.0F))
            .texOffs(82, 94).addBox(-0.4142F, -1.936F, -1.0F, 0.8284F, 1.972F, 2.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.85F, 0.0F, 0.0F, 0.7854F, 0.0F));

        rotor.addOrReplaceChild("bucket_e", CubeListBuilder.create()
            .texOffs(158, 94).addBox(-0.625F, -0.1F, -0.625F, 1.25F, 1.3F, 1.25F, new CubeDeformation(0.0F))
            .texOffs(165, 94).addBox(-0.375F, -0.9F, -0.375F, 0.75F, 2.0F, 0.75F, new CubeDeformation(0.0F))
            .texOffs(0, 100).addBox(-0.275F, -0.4F, -0.275F, 0.55F, 1.4F, 0.55F, new CubeDeformation(0.0F))
            .texOffs(227, 94).addBox(-0.425F, -1.2F, -0.425F, 0.85F, 0.3F, 0.85F, new CubeDeformation(0.0F)), PartPose.offset(3.0F, -0.8F, 0.0F));

        rotor.addOrReplaceChild("bucket_w", CubeListBuilder.create()
            .texOffs(158, 94).addBox(-0.625F, -0.1F, -0.625F, 1.25F, 1.3F, 1.25F, new CubeDeformation(0.0F))
            .texOffs(165, 94).addBox(-0.375F, -0.9F, -0.375F, 0.75F, 2.0F, 0.75F, new CubeDeformation(0.0F))
            .texOffs(4, 100).addBox(-0.275F, -0.4F, -0.275F, 0.55F, 1.4F, 0.55F, new CubeDeformation(0.0F))
            .texOffs(227, 94).addBox(-0.425F, -1.2F, -0.425F, 0.85F, 0.3F, 0.85F, new CubeDeformation(0.0F)), PartPose.offset(-3.0F, -0.8F, 0.0F));

        rotor.addOrReplaceChild("bucket_s", CubeListBuilder.create()
            .texOffs(158, 94).addBox(-0.625F, -0.1F, -0.625F, 1.25F, 1.3F, 1.25F, new CubeDeformation(0.0F))
            .texOffs(165, 94).addBox(-0.375F, -0.9F, -0.375F, 0.75F, 2.0F, 0.75F, new CubeDeformation(0.0F))
            .texOffs(8, 100).addBox(-0.275F, -0.4F, -0.275F, 0.55F, 1.4F, 0.55F, new CubeDeformation(0.0F))
            .texOffs(227, 94).addBox(-0.425F, -1.2F, -0.425F, 0.85F, 0.3F, 0.85F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -0.8F, 3.0F));

        rotor.addOrReplaceChild("bucket_n", CubeListBuilder.create()
            .texOffs(158, 94).addBox(-0.625F, -0.1F, -0.625F, 1.25F, 1.3F, 1.25F, new CubeDeformation(0.0F))
            .texOffs(165, 94).addBox(-0.375F, -0.9F, -0.375F, 0.75F, 2.0F, 0.75F, new CubeDeformation(0.0F))
            .texOffs(12, 100).addBox(-0.275F, -0.4F, -0.275F, 0.55F, 1.4F, 0.55F, new CubeDeformation(0.0F))
            .texOffs(227, 94).addBox(-0.425F, -1.2F, -0.425F, 0.85F, 0.3F, 0.85F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -0.8F, -3.0F));

        chamber.addOrReplaceChild("left_clamp", CubeListBuilder.create()
            .texOffs(68, 94).addBox(-0.6F, -0.6F, -0.9F, 1.1F, 1.3F, 1.8F, new CubeDeformation(0.0F))
            .texOffs(76, 84).addBox(-0.225F, -6.7F, -0.45F, 0.45F, 6.1F, 0.9F, new CubeDeformation(0.0F))
            .texOffs(221, 94).addBox(-0.225F, -7.0F, -0.45F, 1.15F, 0.45F, 0.9F, new CubeDeformation(0.0F))
            .texOffs(237, 94).addBox(0.45F, -6.75F, -0.45F, 0.4F, 0.35F, 0.9F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-5.4F, -1.2F, 0.2F, 0.0F, 0.0F, -0.2443F));

        chamber.addOrReplaceChild("right_clamp", CubeListBuilder.create()
            .texOffs(68, 94).addBox(-0.5F, -0.6F, -0.9F, 1.1F, 1.3F, 1.8F, new CubeDeformation(0.0F))
            .texOffs(76, 84).addBox(-0.225F, -6.7F, -0.45F, 0.45F, 6.1F, 0.9F, new CubeDeformation(0.0F))
            .texOffs(221, 94).addBox(-0.925F, -7.0F, -0.45F, 1.15F, 0.45F, 0.9F, new CubeDeformation(0.0F))
            .texOffs(237, 94).addBox(-0.85F, -6.75F, -0.45F, 0.4F, 0.35F, 0.9F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(5.4F, -1.2F, 0.2F, 0.0F, 0.0F, 0.2443F));

        chamber.addOrReplaceChild("scanner", CubeListBuilder.create()
            .texOffs(80, 84).addBox(-2.1F, 0.0F, -2.1F, 4.2F, 1.3F, 4.2F, new CubeDeformation(0.0F))
            .texOffs(125, 94).addBox(-1.2F, 1.3F, -1.2F, 2.4F, 0.35F, 2.4F, new CubeDeformation(0.0F))
            .texOffs(241, 94).addBox(-0.3F, 1.65F, -0.3F, 0.6F, 0.6F, 0.6F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -10.5F, 0.2F));

        PartDefinition controls = dnaExtractor.addOrReplaceChild("controls", CubeListBuilder.create()
            .texOffs(207, 94).addBox(-6.3F, 12.5F, 3.5F, 1.4F, 0.5F, 1.1F, new CubeDeformation(0.0F))
            .texOffs(10, 94).addBox(-6.15F, 8.9F, 3.5F, 1.1F, 3.6F, 1.1F, new CubeDeformation(0.0F))
            .texOffs(89, 94).addBox(-6.025F, 9.8F, 3.625F, 0.85F, 2.6F, 0.85F, new CubeDeformation(0.0F))
            .texOffs(200, 94).addBox(-6.25F, 8.3F, 3.4F, 1.3F, 0.6F, 1.3F, new CubeDeformation(0.0F))
            .texOffs(245, 94).addBox(-5.775F, 7.95F, 3.85F, 0.35F, 0.35F, 0.8F, new CubeDeformation(0.0F))
            .texOffs(170, 94).addBox(-5.78F, 5.8F, 4.55F, 0.35F, 2.5F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(214, 94).addBox(4.9F, 12.5F, 3.5F, 1.4F, 0.5F, 1.1F, new CubeDeformation(0.0F))
            .texOffs(10, 94).addBox(5.05F, 8.9F, 3.5F, 1.1F, 3.6F, 1.1F, new CubeDeformation(0.0F))
            .texOffs(94, 94).addBox(5.175F, 9.8F, 3.625F, 0.85F, 2.6F, 0.85F, new CubeDeformation(0.0F))
            .texOffs(200, 94).addBox(4.95F, 8.3F, 3.4F, 1.3F, 0.6F, 1.3F, new CubeDeformation(0.0F))
            .texOffs(249, 94).addBox(5.425F, 7.95F, 3.85F, 0.35F, 0.35F, 0.8F, new CubeDeformation(0.0F))
            .texOffs(173, 94).addBox(5.42F, 5.8F, 4.55F, 0.35F, 2.5F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(36, 100).addBox(4.6F, 0.9F, -8.13F, 2.4F, 0.7F, 0.1F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        controls.addOrReplaceChild("console_r1", CubeListBuilder.create()
            .texOffs(94, 34).addBox(-6.4F, -1.5F, -1.4F, 12.8F, 1.5F, 2.6F, new CubeDeformation(0.0F), 0.5F, 0.5F), PartPose.offsetAndRotation(0.0F, 13.5F, -6.3F, 0.384F, 0.0F, 0.0F));

        controls.addOrReplaceChild("status_led", CubeListBuilder.create()
            .texOffs(43, 100).addBox(-0.25F, -0.25F, -0.2F, 0.5F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(5.8F, 1.25F, -8.05F));

        controls.addOrReplaceChild("activity_led", CubeListBuilder.create()
            .texOffs(46, 100).addBox(-0.25F, -0.25F, -0.2F, 0.5F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(6.6F, 1.25F, -8.05F));

        return LayerDefinition.create(meshdefinition, 256, 128);
    }

    @Override
    public void setupAnim(DNAExtractorRenderState state) {
        super.setupAnim(state);
        this.idleAnimation.apply((long) (state.ageInTicks * 50.0F), 1.0F);
        this.processingAnimation.apply(state.extractingState, state.ageInTicks);
    }
}
