package com.coolerpromc.ancientcreature.client.entity.model.block;

import com.coolerpromc.ancientcreature.client.entity.animation.block.EmbryogenesisChamberAnimation;
import com.coolerpromc.ancientcreature.client.entity.state.block.EmbryogenesisChamberRenderState;
import net.minecraft.client.animation.KeyframeAnimation;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

// Generated by art/texgen/machines/make_machines.py from art/texgen/machines/defs/embryogenesis_chamber.py - edit that, not this file.
public class EmbryogenesisChamberModel extends EntityModel<EmbryogenesisChamberRenderState> {
    private final KeyframeAnimation processingAnimation;
    private final KeyframeAnimation idleAnimation;

    public EmbryogenesisChamberModel(ModelPart root) {
        super(root);
        this.processingAnimation = EmbryogenesisChamberAnimation.PROCESSING.bake(root);
        this.idleAnimation = EmbryogenesisChamberAnimation.IDLE.bake(root);
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();

        PartDefinition embryogenesisChamber = partdefinition.addOrReplaceChild("embryogenesis_chamber", CubeListBuilder.create(), PartPose.offset(0.0F, 24.0F, 0.0F));

        embryogenesisChamber.addOrReplaceChild("chassis", CubeListBuilder.create()
            .texOffs(61, 98).addBox(-7.6F, -0.6F, -7.6F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(61, 98).addBox(-7.6F, -0.6F, 5.9F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(61, 98).addBox(5.9F, -0.6F, -7.6F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(61, 98).addBox(5.9F, -0.6F, 5.9F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(76, 40).addBox(-8.0F, -3.0F, -7.7F, 16.0F, 2.4F, 15.7F, new CubeDeformation(0.0F))
            .texOffs(0, 0).addBox(-7.75F, -7.0F, -7.3F, 15.5F, 4.0F, 15.3F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(0, 44).addBox(-7.4F, -6.7F, -7.6F, 14.8F, 3.4F, 0.35F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(141, 40).addBox(-8.0F, -7.7F, -8.0F, 16.0F, 0.7F, 16.0F, new CubeDeformation(0.0F))
            .texOffs(0, 20).addBox(-8.0F, -20.7F, 5.4F, 16.0F, 13.0F, 2.6F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(233, 40).addBox(-8.0F, -20.7F, -7.6F, 1.4F, 13.0F, 1.6F, new CubeDeformation(0.0F))
            .texOffs(241, 40).addBox(6.6F, -20.7F, -7.6F, 1.4F, 13.0F, 1.6F, new CubeDeformation(0.0F))
            .texOffs(63, 0).addBox(-8.0F, -24.0F, -7.6F, 16.0F, 3.3F, 15.6F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(139, 98).addBox(-3.5F, -20.7F, 4.6F, 0.6F, 0.7F, 0.8F, new CubeDeformation(0.0F))
            .texOffs(143, 98).addBox(2.9F, -20.7F, 4.6F, 0.6F, 0.7F, 0.8F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition incubationVessel = embryogenesisChamber.addOrReplaceChild("incubation_vessel", CubeListBuilder.create()
            .texOffs(109, 88).addBox(-5.3F, 4.7F, -2.1953F, 10.6F, 1.1F, 4.3907F, new CubeDeformation(0.0F))
            .texOffs(0, 74).addBox(-2.1953F, 4.688F, -5.3F, 4.3907F, 1.124F, 10.6F, new CubeDeformation(0.0F))
            .texOffs(171, 88).addBox(-5.3F, -7.2F, -2.1953F, 10.6F, 1.2F, 4.3907F, new CubeDeformation(0.0F))
            .texOffs(62, 74).addBox(-2.1953F, -7.212F, -5.3F, 4.3907F, 1.224F, 10.6F, new CubeDeformation(0.0F))
            .texOffs(127, 74).addBox(-2.0692F, -6.0F, -4.8F, 4.1385F, 10.7F, 0.18F, new CubeDeformation(0.0F))
            .texOffs(137, 74).addBox(-2.0692F, -6.0F, 4.62F, 4.1385F, 10.7F, 0.18F, new CubeDeformation(0.0F))
            .texOffs(207, 40).addBox(-3.1F, -5.5F, -3.1F, 6.2F, 10.0F, 6.2F, new CubeDeformation(0.0F))
            .texOffs(124, 74).addBox(3.3252F, -6.0F, 3.3252F, 0.35F, 10.7F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(124, 74).addBox(-3.6752F, -6.0F, 3.3252F, 0.35F, 10.7F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(124, 74).addBox(-3.6752F, -6.0F, -3.6752F, 0.35F, 10.7F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(124, 74).addBox(3.3252F, -6.0F, -3.6752F, 0.35F, 10.7F, 0.35F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -13.5F, 0.5F));

        incubationVessel.addOrReplaceChild("collar_bottom_r1", CubeListBuilder.create()
            .texOffs(140, 88).addBox(-5.3F, -1.124F, -2.1953F, 10.6F, 1.148F, 4.3907F, new CubeDeformation(0.0F))
            .texOffs(31, 74).addBox(-2.1953F, -1.136F, -5.3F, 4.3907F, 1.172F, 10.6F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 5.8F, 0.0F, 0.0F, 0.7854F, 0.0F));

        incubationVessel.addOrReplaceChild("collar_top_r1", CubeListBuilder.create()
            .texOffs(202, 88).addBox(-5.3F, -1.224F, -2.1953F, 10.6F, 1.248F, 4.3907F, new CubeDeformation(0.0F))
            .texOffs(93, 74).addBox(-2.1953F, -1.236F, -5.3F, 4.3907F, 1.272F, 10.6F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -6.0F, 0.0F, 0.0F, 0.7854F, 0.0F));

        incubationVessel.addOrReplaceChild("glass_1", CubeListBuilder.create()
            .texOffs(147, 74).addBox(-2.0692F, -10.7F, -4.8F, 4.1385F, 10.7F, 0.18F, new CubeDeformation(0.0F))
            .texOffs(157, 74).addBox(-2.0692F, -10.7F, 4.62F, 4.1385F, 10.7F, 0.18F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 4.7F, 0.0F, 0.0F, 0.7854F, 0.0F));

        incubationVessel.addOrReplaceChild("glass_2", CubeListBuilder.create()
            .texOffs(167, 74).addBox(-2.0692F, -10.7F, -4.8F, 4.1385F, 10.7F, 0.18F, new CubeDeformation(0.0F))
            .texOffs(177, 74).addBox(-2.0692F, -10.7F, 4.62F, 4.1385F, 10.7F, 0.18F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 4.7F, 0.0F, 0.0F, 1.5708F, 0.0F));

        incubationVessel.addOrReplaceChild("glass_3", CubeListBuilder.create()
            .texOffs(187, 74).addBox(-2.0692F, -10.7F, -4.8F, 4.1385F, 10.7F, 0.18F, new CubeDeformation(0.0F))
            .texOffs(197, 74).addBox(-2.0692F, -10.7F, 4.62F, 4.1385F, 10.7F, 0.18F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 4.7F, 0.0F, 0.0F, 2.3562F, 0.0F));

        PartDefinition embryoCore = incubationVessel.addOrReplaceChild("embryo_core", CubeListBuilder.create()
            .texOffs(91, 98).addBox(-0.5F, 1.3F, -0.6F, 1.2F, 1.1F, 1.2F, new CubeDeformation(0.0F))
            .texOffs(101, 98).addBox(-0.75F, 2.2F, 0.25F, 0.3F, 2.6F, 0.3F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -0.5F, 0.0F));

        embryoCore.addOrReplaceChild("embryo_torso", CubeListBuilder.create()
            .texOffs(0, 98).addBox(-1.4F, -1.1F, -0.95F, 2.8F, 2.1F, 1.9F, new CubeDeformation(0.0F))
            .texOffs(69, 98).addBox(-0.6F, 0.9F, -0.75F, 1.6F, 0.6F, 1.5F, new CubeDeformation(0.0F))
            .texOffs(151, 98).addBox(0.525F, 0.8F, -1.0F, 0.55F, 0.9F, 0.5F, new CubeDeformation(0.0F))
            .texOffs(151, 98).addBox(0.525F, 0.8F, 0.5F, 0.55F, 0.9F, 0.5F, new CubeDeformation(0.0F))
            .texOffs(151, 98).addBox(-1.175F, 0.8F, -1.0F, 0.55F, 0.9F, 0.5F, new CubeDeformation(0.0F))
            .texOffs(151, 98).addBox(-1.175F, 0.8F, 0.5F, 0.55F, 0.9F, 0.5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.1745F));

        embryoCore.addOrReplaceChild("embryo_head", CubeListBuilder.create()
            .texOffs(11, 98).addBox(-0.2F, -1.0F, -0.95F, 2.0F, 1.9F, 1.9F, new CubeDeformation(0.0F))
            .texOffs(84, 98).addBox(1.6F, -0.15F, -0.6F, 1.3F, 1.0F, 1.2F, new CubeDeformation(0.0F))
            .texOffs(27, 104).addBox(0.45F, -0.5F, -1.0F, 0.6F, 0.6F, 0.1F, new CubeDeformation(0.0F))
            .texOffs(27, 104).addBox(0.45F, -0.5F, 0.9F, 0.6F, 0.6F, 0.1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.3F, -0.6F, 0.0F, 0.0F, 0.0F, 0.8727F));

        PartDefinition embryoTail = embryoCore.addOrReplaceChild("embryo_tail", CubeListBuilder.create()
            .texOffs(77, 98).addBox(-1.4F, -0.6F, -0.6F, 1.5F, 1.2F, 1.2F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.3F, 0.5F, 0.0F, 0.0F, 0.0F, -0.7854F));

        embryoTail.addOrReplaceChild("embryo_tail_tip", CubeListBuilder.create()
            .texOffs(128, 98).addBox(-1.3F, -0.45F, -0.45F, 1.4F, 0.85F, 0.9F, new CubeDeformation(0.0F))
            .texOffs(134, 98).addBox(-2.2F, -0.3F, -0.3F, 1.0F, 0.55F, 0.6F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.3F, 0.1F, 0.0F, 0.0F, 0.0F, -1.0472F));

        embryogenesisChamber.addOrReplaceChild("cradle", CubeListBuilder.create()
            .texOffs(62, 88).addBox(-3.2F, -0.15F, -3.2F, 6.4F, 0.35F, 6.4F, new CubeDeformation(0.0F))
            .texOffs(41, 98).addBox(-1.0F, -0.35F, -1.0F, 2.0F, 0.2F, 2.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -9.0F, 0.5F));

        embryogenesisChamber.addOrReplaceChild("bubbles", CubeListBuilder.create()
            .texOffs(30, 104).addBox(-1.775F, -0.45F, -1.375F, 0.35F, 0.35F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(42, 104).addBox(1.275F, -1.55F, -0.725F, 0.25F, 0.25F, 0.25F, new CubeDeformation(0.0F))
            .texOffs(33, 104).addBox(-0.95F, -2.8F, 1.45F, 0.3F, 0.3F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(36, 104).addBox(1.75F, -0.9F, 1.25F, 0.3F, 0.3F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(45, 104).addBox(0.175F, -3.85F, -2.225F, 0.25F, 0.25F, 0.25F, new CubeDeformation(0.0F))
            .texOffs(50, 104).addBox(-2.3F, -4.7F, 0.3F, 0.2F, 0.2F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -9.3F, 0.5F));

        embryogenesisChamber.addOrReplaceChild("injector_left", CubeListBuilder.create()
            .texOffs(20, 98).addBox(-0.45F, 0.0F, -0.45F, 0.9F, 2.5F, 0.9F, new CubeDeformation(0.0F))
            .texOffs(116, 98).addBox(-0.6F, 2.5F, -0.6F, 1.2F, 0.4F, 1.2F, new CubeDeformation(0.0F))
            .texOffs(104, 98).addBox(-0.09F, 2.9F, -0.09F, 0.18F, 2.4F, 0.18F, new CubeDeformation(0.0F))
            .texOffs(7, 104).addBox(-0.25F, 0.8F, -0.25F, 0.5F, 0.5F, 0.5F, new CubeDeformation(0.0F)), PartPose.offset(-3.0F, -19.5F, -1.1F));

        embryogenesisChamber.addOrReplaceChild("injector_right", CubeListBuilder.create()
            .texOffs(25, 98).addBox(-0.45F, 0.0F, -0.45F, 0.9F, 2.5F, 0.9F, new CubeDeformation(0.0F))
            .texOffs(122, 98).addBox(-0.6F, 2.5F, -0.6F, 1.2F, 0.4F, 1.2F, new CubeDeformation(0.0F))
            .texOffs(106, 98).addBox(-0.09F, 2.9F, -0.09F, 0.18F, 2.4F, 0.18F, new CubeDeformation(0.0F))
            .texOffs(11, 104).addBox(-0.25F, 0.8F, -0.25F, 0.5F, 0.5F, 0.5F, new CubeDeformation(0.0F)), PartPose.offset(3.0F, -19.5F, -1.1F));

        PartDefinition fluidRing = embryogenesisChamber.addOrReplaceChild("fluid_ring", CubeListBuilder.create()
            .texOffs(158, 98).addBox(-2.1611F, -0.15F, -5.0F, 4.3221F, 0.35F, 0.2F, new CubeDeformation(0.0F))
            .texOffs(169, 98).addBox(-2.1611F, -0.15F, 4.8F, 4.3221F, 0.35F, 0.2F, new CubeDeformation(0.0F))
            .texOffs(147, 98).addBox(4.825F, -0.4F, -0.275F, 0.55F, 0.8F, 0.55F, new CubeDeformation(0.0F))
            .texOffs(147, 98).addBox(-0.275F, -0.4F, 4.825F, 0.55F, 0.8F, 0.55F, new CubeDeformation(0.0F))
            .texOffs(147, 98).addBox(-5.375F, -0.4F, -0.275F, 0.55F, 0.8F, 0.55F, new CubeDeformation(0.0F))
            .texOffs(147, 98).addBox(-0.275F, -0.4F, -5.375F, 0.55F, 0.8F, 0.55F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -17.6F, 0.5F));

        fluidRing.addOrReplaceChild("ring_1", CubeListBuilder.create()
            .texOffs(180, 98).addBox(-2.1611F, -0.35F, -5.0F, 4.3221F, 0.35F, 0.2F, new CubeDeformation(0.0F))
            .texOffs(191, 98).addBox(-2.1611F, -0.35F, 4.8F, 4.3221F, 0.35F, 0.2F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.2F, 0.0F, 0.0F, 0.7854F, 0.0F));

        fluidRing.addOrReplaceChild("ring_2", CubeListBuilder.create()
            .texOffs(202, 98).addBox(-2.1611F, -0.35F, -5.0F, 4.3221F, 0.35F, 0.2F, new CubeDeformation(0.0F))
            .texOffs(213, 98).addBox(-2.1611F, -0.35F, 4.8F, 4.3221F, 0.35F, 0.2F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.2F, 0.0F, 0.0F, 1.5708F, 0.0F));

        fluidRing.addOrReplaceChild("ring_3", CubeListBuilder.create()
            .texOffs(224, 98).addBox(-2.1611F, -0.35F, -5.0F, 4.3221F, 0.35F, 0.2F, new CubeDeformation(0.0F))
            .texOffs(235, 98).addBox(-2.1611F, -0.35F, 4.8F, 4.3221F, 0.35F, 0.2F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.2F, 0.0F, 0.0F, 2.3562F, 0.0F));

        PartDefinition controls = embryogenesisChamber.addOrReplaceChild("controls", CubeListBuilder.create()
            .texOffs(97, 98).addBox(-4.9F, -9.9F, -5.9F, 0.6F, 2.2F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(108, 98).addBox(-5.4F, -8.0F, -6.4F, 1.6F, 0.3F, 1.6F, new CubeDeformation(0.0F))
            .texOffs(246, 98).addBox(2.8F, -6.1F, -7.72F, 3.6F, 0.8F, 0.1F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        controls.addOrReplaceChild("vitals_screen", CubeListBuilder.create()
            .texOffs(45, 44).addBox(-1.9F, -2.5F, -0.325F, 3.8F, 2.6F, 0.45F, new CubeDeformation(0.0F), 0.5F, 0.5F), PartPose.offsetAndRotation(-4.6F, -9.9F, -5.8F, 0.2793F, 0.0F, 0.0F));

        PartDefinition statusLights = controls.addOrReplaceChild("status_lights", CubeListBuilder.create(), PartPose.offset(4.6F, -5.5F, -7.7F));

        statusLights.addOrReplaceChild("status_light_0", CubeListBuilder.create()
            .texOffs(15, 104).addBox(-0.275F, -0.25F, -0.15F, 0.55F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(-1.3F, -0.2F, -0.05F));

        statusLights.addOrReplaceChild("status_light_1", CubeListBuilder.create()
            .texOffs(18, 104).addBox(-0.275F, -0.25F, -0.15F, 0.55F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(-0.4F, -0.2F, -0.05F));

        statusLights.addOrReplaceChild("status_light_2", CubeListBuilder.create()
            .texOffs(21, 104).addBox(-0.275F, -0.25F, -0.15F, 0.55F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(0.5F, -0.2F, -0.05F));

        statusLights.addOrReplaceChild("status_light_3", CubeListBuilder.create()
            .texOffs(24, 104).addBox(-0.275F, -0.25F, -0.15F, 0.55F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(1.4F, -0.2F, -0.05F));

        PartDefinition nutrientTank = controls.addOrReplaceChild("nutrient_tank", CubeListBuilder.create()
            .texOffs(30, 98).addBox(-1.2F, -0.5F, -1.2F, 2.4F, 0.5F, 2.4F, new CubeDeformation(0.0F))
            .texOffs(233, 88).addBox(-0.9F, -4.3F, -0.9F, 1.8F, 3.8F, 1.8F, new CubeDeformation(0.0F))
            .texOffs(242, 88).addBox(-0.725F, -3.2F, -0.725F, 1.45F, 2.6F, 1.45F, new CubeDeformation(0.0F))
            .texOffs(51, 98).addBox(-1.0F, -4.85F, -1.0F, 2.0F, 0.55F, 2.0F, new CubeDeformation(0.0F))
            .texOffs(155, 98).addBox(-0.2F, -6.45F, -0.2F, 0.4F, 1.6F, 0.4F, new CubeDeformation(0.0F))
            .texOffs(0, 104).addBox(-2.2F, -6.5F, -0.2F, 2.4F, 0.4F, 0.4F, new CubeDeformation(0.0F)), PartPose.offset(5.5F, -7.7F, -5.5F));

        nutrientTank.addOrReplaceChild("tank_bubble", CubeListBuilder.create()
            .texOffs(39, 104).addBox(-0.35F, -0.2F, -0.25F, 0.3F, 0.3F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(48, 104).addBox(0.19F, -0.82F, 0.09F, 0.22F, 0.22F, 0.22F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -0.9F, 0.0F));

        return LayerDefinition.create(meshdefinition, 256, 128);
    }

    @Override
    public void setupAnim(EmbryogenesisChamberRenderState state) {
        super.setupAnim(state);
        this.idleAnimation.apply((long) (state.ageInTicks * 50.0F), 1.0F);
        this.processingAnimation.apply(state.processingState, state.ageInTicks);
    }
}
