package com.coolerpromc.ancientcreature.client.entity.model.block;

import com.coolerpromc.ancientcreature.client.entity.animation.block.FossilCleaningTableAnimation;
import com.coolerpromc.ancientcreature.client.entity.state.block.FossilCleaningTableRenderState;
import net.minecraft.client.animation.KeyframeAnimation;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

// Generated by art/texgen/machines/make_machines.py from art/texgen/machines/defs/fossil_cleaning_table.py - edit that, not this file.
public class FossilCleaningTableModel extends EntityModel<FossilCleaningTableRenderState> {
    private final KeyframeAnimation processingAnimation;
    private final KeyframeAnimation idleAnimation;

    public FossilCleaningTableModel(ModelPart root) {
        super(root);
        this.processingAnimation = FossilCleaningTableAnimation.PROCESSING.bake(root);
        this.idleAnimation = FossilCleaningTableAnimation.IDLE.bake(root);
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();

        PartDefinition fossilCleaningTable = partdefinition.addOrReplaceChild("fossil_cleaning_table", CubeListBuilder.create(), PartPose.offset(0.0F, 24.0F, 0.0F));

        fossilCleaningTable.addOrReplaceChild("frame", CubeListBuilder.create()
            .texOffs(180, 0).addBox(-7.35F, -9.5F, -7.35F, 1.3F, 9.0F, 1.3F, new CubeDeformation(0.0F))
            .texOffs(20, 32).addBox(-7.6F, -0.5F, -7.6F, 1.8F, 0.5F, 1.8F, new CubeDeformation(0.0F))
            .texOffs(180, 0).addBox(-7.35F, -9.5F, 6.05F, 1.3F, 9.0F, 1.3F, new CubeDeformation(0.0F))
            .texOffs(20, 32).addBox(-7.6F, -0.5F, 5.8F, 1.8F, 0.5F, 1.8F, new CubeDeformation(0.0F))
            .texOffs(180, 0).addBox(6.05F, -9.5F, -7.35F, 1.3F, 9.0F, 1.3F, new CubeDeformation(0.0F))
            .texOffs(20, 32).addBox(5.8F, -0.5F, -7.6F, 1.8F, 0.5F, 1.8F, new CubeDeformation(0.0F))
            .texOffs(180, 0).addBox(6.05F, -9.5F, 6.05F, 1.3F, 9.0F, 1.3F, new CubeDeformation(0.0F))
            .texOffs(20, 32).addBox(5.8F, -0.5F, 5.8F, 1.8F, 0.5F, 1.8F, new CubeDeformation(0.0F))
            .texOffs(215, 20).addBox(-6.05F, -10.0F, -7.2F, 12.1F, 1.4F, 0.9F, new CubeDeformation(0.0F))
            .texOffs(215, 20).addBox(-6.05F, -10.0F, 6.3F, 12.1F, 1.4F, 0.9F, new CubeDeformation(0.0F))
            .texOffs(102, 0).addBox(-7.2F, -10.0F, -6.05F, 0.9F, 1.4F, 12.1F, new CubeDeformation(0.0F))
            .texOffs(102, 0).addBox(6.3F, -10.0F, -6.05F, 0.9F, 1.4F, 12.1F, new CubeDeformation(0.0F))
            .texOffs(130, 0).addBox(-6.05F, -3.2F, -6.05F, 12.1F, 0.6F, 12.1F, new CubeDeformation(0.0F))
            .texOffs(80, 32).addBox(-6.05F, -2.6F, -7.0F, 12.1F, 0.6F, 0.7F, new CubeDeformation(0.0F))
            .texOffs(80, 32).addBox(-6.05F, -2.6F, 6.3F, 12.1F, 0.6F, 0.7F, new CubeDeformation(0.0F))
            .texOffs(43, 10).addBox(-4.2F, -10.1F, -7.55F, 8.4F, 1.9F, 0.5F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(224, 32).addBox(0.6F, -9.3F, -7.95F, 2.4F, 0.45F, 0.4F, new CubeDeformation(0.0F))
            .texOffs(33, 0).addBox(-5.4F, -5.8F, -4.6F, 4.6F, 2.6F, 4.0F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(137, 20).addBox(-5.0F, -5.9F, -4.2F, 3.8F, 0.5F, 3.2F, new CubeDeformation(0.0F))
            .texOffs(123, 20).addBox(1.8F, -4.8F, -2.6F, 3.2F, 1.6F, 3.2F, new CubeDeformation(0.0F))
            .texOffs(29, 32).addBox(2.1F, -5.7F, -2.2F, 1.8F, 0.9F, 1.6F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        fossilCleaningTable.addOrReplaceChild("cleaning_surface", CubeListBuilder.create()
            .texOffs(0, 0).addBox(-8.0F, -12.0F, -8.0F, 16.0F, 2.0F, 16.0F, new CubeDeformation(0.0F))
            .texOffs(36, 20).addBox(-7.6F, -15.6F, 6.0F, 15.2F, 3.6F, 1.6F, new CubeDeformation(0.0F))
            .texOffs(178, 20).addBox(-7.9F, -16.1F, 5.8F, 15.8F, 0.5F, 2.0F, new CubeDeformation(0.0F))
            .texOffs(107, 32).addBox(-5.4F, -13.0F, -5.8F, 10.0F, 1.0F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(130, 32).addBox(-5.4F, -13.0F, 3.6F, 10.0F, 1.0F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(224, 0).addBox(-5.4F, -13.0F, -5.2F, 0.6F, 1.0F, 8.8F, new CubeDeformation(0.0F))
            .texOffs(0, 20).addBox(4.0F, -13.0F, -5.2F, 0.6F, 1.0F, 8.8F, new CubeDeformation(0.0F))
            .texOffs(187, 0).addBox(-4.8F, -12.6F, -5.2F, 8.8F, 0.6F, 8.8F, new CubeDeformation(0.0F))
            .texOffs(71, 32).addBox(-6.6F, -15.0F, 5.75F, 0.35F, 2.4F, 0.25F, new CubeDeformation(0.0F))
            .texOffs(250, 32).addBox(-6.75F, -14.95F, 5.7F, 0.65F, 0.35F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(74, 32).addBox(-5.6F, -15.2F, 5.75F, 0.3F, 2.2F, 0.25F, new CubeDeformation(0.0F))
            .texOffs(238, 32).addBox(-5.95F, -15.35F, 5.7F, 1.0F, 0.5F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(77, 32).addBox(-4.5F, -15.2F, 5.75F, 0.25F, 2.0F, 0.25F, new CubeDeformation(0.0F))
            .texOffs(36, 10).addBox(4.2F, -15.1F, 5.7F, 2.6F, 2.6F, 0.3F, new CubeDeformation(0.0F), 0.5F, 0.5F), PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition toolsAndFossil = fossilCleaningTable.addOrReplaceChild("tools_and_fossil", CubeListBuilder.create()
            .texOffs(231, 32).addBox(4.8F, -12.35F, -6.6F, 2.4F, 0.35F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(253, 32).addBox(7.2F, -12.3F, -6.55F, 0.6F, 0.25F, 0.25F, new CubeDeformation(0.0F))
            .texOffs(37, 32).addBox(5.2F, -12.45F, -3.4F, 0.45F, 0.45F, 2.4F, new CubeDeformation(0.0F))
            .texOffs(58, 32).addBox(4.7F, -12.95F, -4.5F, 1.4F, 0.95F, 1.1F, new CubeDeformation(0.0F))
            .texOffs(44, 32).addBox(-6.8F, -12.2F, -6.6F, 0.2F, 0.2F, 2.6F, new CubeDeformation(0.0F))
            .texOffs(10, 32).addBox(-7.2F, -12.7F, 2.2F, 2.0F, 0.7F, 2.0F, new CubeDeformation(0.0F))
            .texOffs(179, 32).addBox(-6.9F, -12.75F, 2.5F, 1.4F, 0.25F, 1.4F, new CubeDeformation(0.0F))
            .texOffs(199, 32).addBox(-3.5F, -12.85F, 1.1F, 1.4F, 0.25F, 1.0F, new CubeDeformation(0.0F))
            .texOffs(205, 32).addBox(2.3F, -12.8F, 1.35F, 1.0F, 0.2F, 0.9F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        toolsAndFossil.addOrReplaceChild("fossil_skull", CubeListBuilder.create()
            .texOffs(0, 32).addBox(-1.2F, -0.95F, -0.85F, 2.6F, 1.05F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(186, 32).addBox(1.3F, -0.65F, -0.55F, 1.6F, 0.75F, 1.1F, new CubeDeformation(0.0F))
            .texOffs(243, 20).addBox(-1.0F, -0.15F, -0.95F, 3.6F, 0.35F, 1.9F, new CubeDeformation(0.0F))
            .texOffs(246, 32).addBox(-0.2F, -0.96F, -0.6F, 0.6F, 0.06F, 0.55F, new CubeDeformation(0.0F))
            .texOffs(0, 36).addBox(2.1F, -0.66F, -0.2F, 0.4F, 0.06F, 0.4F, new CubeDeformation(0.0F))
            .texOffs(16, 36).addBox(1.4F, 0.05F, -0.95F, 0.12F, 0.3F, 0.1F, new CubeDeformation(0.0F))
            .texOffs(16, 36).addBox(1.72F, 0.05F, -0.95F, 0.12F, 0.3F, 0.1F, new CubeDeformation(0.0F))
            .texOffs(16, 36).addBox(2.04F, 0.05F, -0.95F, 0.12F, 0.3F, 0.1F, new CubeDeformation(0.0F))
            .texOffs(16, 36).addBox(2.36F, 0.05F, -0.95F, 0.12F, 0.3F, 0.1F, new CubeDeformation(0.0F))
            .texOffs(16, 36).addBox(2.68F, 0.05F, -0.95F, 0.12F, 0.3F, 0.1F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.6F, -12.6F, -1.0F, 0.0F, 0.3491F, 0.0F));

        PartDefinition fossilSpine = toolsAndFossil.addOrReplaceChild("fossil_spine", CubeListBuilder.create()
            .texOffs(220, 32).addBox(-1.1F, -0.45F, -0.375F, 0.6F, 0.55F, 0.75F, new CubeDeformation(0.0F))
            .texOffs(6, 36).addBox(-0.9F, -0.8F, -0.15F, 0.2F, 0.35F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(220, 32).addBox(-1.85F, -0.45F, -0.375F, 0.6F, 0.55F, 0.75F, new CubeDeformation(0.0F))
            .texOffs(6, 36).addBox(-1.65F, -0.8F, -0.15F, 0.2F, 0.35F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(220, 32).addBox(-2.6F, -0.45F, -0.375F, 0.6F, 0.55F, 0.75F, new CubeDeformation(0.0F))
            .texOffs(6, 36).addBox(-2.4F, -0.8F, -0.15F, 0.2F, 0.35F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(220, 32).addBox(-3.35F, -0.45F, -0.375F, 0.6F, 0.55F, 0.75F, new CubeDeformation(0.0F))
            .texOffs(6, 36).addBox(-3.15F, -0.8F, -0.15F, 0.2F, 0.35F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(220, 32).addBox(-4.1F, -0.45F, -0.375F, 0.6F, 0.55F, 0.75F, new CubeDeformation(0.0F))
            .texOffs(6, 36).addBox(-3.9F, -0.8F, -0.15F, 0.2F, 0.35F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(220, 32).addBox(-4.85F, -0.45F, -0.375F, 0.6F, 0.55F, 0.75F, new CubeDeformation(0.0F))
            .texOffs(6, 36).addBox(-4.65F, -0.8F, -0.15F, 0.2F, 0.35F, 0.3F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.4F, -12.6F, -0.6F, 0.0F, -0.2094F, 0.0F));

        fossilSpine.addOrReplaceChild("rib_0_l", CubeListBuilder.create()
            .texOffs(65, 32).addBox(-0.12F, -0.1F, -2.2F, 0.24F, 0.25F, 1.85F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.4F, -0.1F, 0.0F, 0.0F, -0.3142F, 0.0F));

        fossilSpine.addOrReplaceChild("rib_0_r", CubeListBuilder.create()
            .texOffs(65, 32).addBox(-0.12F, -0.1F, 0.35F, 0.24F, 0.25F, 1.85F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-1.4F, -0.1F, 0.0F, 0.0F, 0.3142F, 0.0F));

        fossilSpine.addOrReplaceChild("rib_1_l", CubeListBuilder.create()
            .texOffs(65, 32).addBox(-0.12F, -0.1F, -2.2F, 0.24F, 0.25F, 1.85F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.15F, -0.1F, 0.0F, 0.0F, -0.3142F, 0.0F));

        fossilSpine.addOrReplaceChild("rib_1_r", CubeListBuilder.create()
            .texOffs(65, 32).addBox(-0.12F, -0.1F, 0.35F, 0.24F, 0.25F, 1.85F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.15F, -0.1F, 0.0F, 0.0F, 0.3142F, 0.0F));

        fossilSpine.addOrReplaceChild("rib_2_l", CubeListBuilder.create()
            .texOffs(65, 32).addBox(-0.12F, -0.1F, -2.2F, 0.24F, 0.25F, 1.85F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.9F, -0.1F, 0.0F, 0.0F, -0.3142F, 0.0F));

        fossilSpine.addOrReplaceChild("rib_2_r", CubeListBuilder.create()
            .texOffs(65, 32).addBox(-0.12F, -0.1F, 0.35F, 0.24F, 0.25F, 1.85F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-2.9F, -0.1F, 0.0F, 0.0F, 0.3142F, 0.0F));

        fossilSpine.addOrReplaceChild("rib_3_l", CubeListBuilder.create()
            .texOffs(65, 32).addBox(-0.12F, -0.1F, -2.2F, 0.24F, 0.25F, 1.85F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-3.65F, -0.1F, 0.0F, 0.0F, -0.3142F, 0.0F));

        fossilSpine.addOrReplaceChild("rib_3_r", CubeListBuilder.create()
            .texOffs(65, 32).addBox(-0.12F, -0.1F, 0.35F, 0.24F, 0.25F, 1.85F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-3.65F, -0.1F, 0.0F, 0.0F, 0.3142F, 0.0F));

        toolsAndFossil.addOrReplaceChild("brush", CubeListBuilder.create()
            .texOffs(193, 32).addBox(-0.85F, -0.6F, -0.375F, 1.7F, 0.75F, 0.75F, new CubeDeformation(0.0F))
            .texOffs(210, 32).addBox(-0.65F, -1.15F, -0.3F, 1.3F, 0.55F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(171, 20).addBox(-0.25F, -4.35F, -0.25F, 0.5F, 3.2F, 0.5F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.2F, -12.9F, -2.6F, 0.6981F, 0.0F, 0.0F));

        toolsAndFossil.addOrReplaceChild("dust", CubeListBuilder.create()
            .texOffs(3, 36).addBox(-1.05F, 0.5F, 0.15F, 0.3F, 0.3F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(9, 36).addBox(0.675F, 0.55F, -0.325F, 0.25F, 0.25F, 0.25F, new CubeDeformation(0.0F))
            .texOffs(14, 36).addBox(-0.4F, 0.6F, -0.7F, 0.2F, 0.2F, 0.2F, new CubeDeformation(0.0F))
            .texOffs(12, 36).addBox(0.39F, 0.58F, 0.39F, 0.22F, 0.22F, 0.22F, new CubeDeformation(0.0F)), PartPose.offset(0.2F, -12.9F, -2.6F));

        PartDefinition lamp = toolsAndFossil.addOrReplaceChild("lamp", CubeListBuilder.create()
            .texOffs(51, 32).addBox(-0.6F, -0.2F, -0.7F, 1.2F, 0.7F, 1.4F, new CubeDeformation(0.0F))
            .texOffs(175, 20).addBox(-0.225F, -3.6F, -0.225F, 0.45F, 3.4F, 0.45F, new CubeDeformation(0.0F)), PartPose.offset(6.4F, -16.1F, 6.6F));

        PartDefinition lampArm = lamp.addOrReplaceChild("lamp_arm", CubeListBuilder.create()
            .texOffs(20, 20).addBox(-0.2F, -0.2F, -6.8F, 0.4F, 0.4F, 6.8F, new CubeDeformation(0.0F))
            .texOffs(215, 32).addBox(-0.4F, -0.4F, -0.4F, 0.8F, 0.8F, 0.8F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -3.4F, 0.0F, 0.2443F, 0.6981F, 0.0F));

        PartDefinition lampHead = lampArm.addOrReplaceChild("lamp_head", CubeListBuilder.create()
            .texOffs(153, 32).addBox(-1.4F, 0.05F, -0.5799F, 2.8F, 0.75F, 1.1598F, new CubeDeformation(0.0F))
            .texOffs(153, 20).addBox(-0.5799F, 0.038F, -1.4F, 1.1598F, 0.774F, 2.8F, new CubeDeformation(0.0F))
            .texOffs(171, 32).addBox(-0.85F, 0.8F, -0.85F, 1.7F, 0.15F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(242, 32).addBox(-0.3F, -0.3F, -0.3F, 0.6F, 0.4F, 0.6F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, -6.8F, -0.2443F, 0.0F, 0.0F));

        lampHead.addOrReplaceChild("lamp_shade_r1", CubeListBuilder.create()
            .texOffs(162, 32).addBox(-1.4F, -0.774F, -0.5799F, 2.8F, 0.798F, 1.1598F, new CubeDeformation(0.0F))
            .texOffs(162, 20).addBox(-0.5799F, -0.786F, -1.4F, 1.1598F, 0.822F, 2.8F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.8F, 0.0F, 0.0F, 0.7854F, 0.0F));

        return LayerDefinition.create(meshdefinition, 256, 64);
    }

    @Override
    public void setupAnim(FossilCleaningTableRenderState state) {
        super.setupAnim(state);
        this.idleAnimation.apply((long) (state.ageInTicks * 50.0F), 1.0F);
        this.processingAnimation.apply(state.cleaningState, state.ageInTicks);
    }
}
