package com.coolerpromc.ancientcreature.client.entity.model.block;

import com.coolerpromc.ancientcreature.client.entity.animation.block.FossilIdentificationChamberAnimation;
import com.coolerpromc.ancientcreature.client.entity.state.block.FossilIdentificationChamberRenderState;
import net.minecraft.client.animation.KeyframeAnimation;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

// Generated by art/texgen/machines/make_machines.py from art/texgen/machines/defs/fossil_identification_chamber.py - edit that, not this file.
public class FossilIdentificationChamberModel extends EntityModel<FossilIdentificationChamberRenderState> {
    private final KeyframeAnimation processingAnimation;
    private final KeyframeAnimation idleAnimation;

    public FossilIdentificationChamberModel(ModelPart root) {
        super(root);
        this.processingAnimation = FossilIdentificationChamberAnimation.PROCESSING.bake(root);
        this.idleAnimation = FossilIdentificationChamberAnimation.IDLE.bake(root);
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();

        PartDefinition fossilIdentifyingChamber = partdefinition.addOrReplaceChild("fossil_identifying_chamber", CubeListBuilder.create(), PartPose.offset(0.0F, 0.0F, 0.0F));

        fossilIdentifyingChamber.addOrReplaceChild("frame", CubeListBuilder.create()
            .texOffs(131, 120).addBox(-7.6F, 23.4F, -7.6F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(131, 120).addBox(-7.6F, 23.4F, 5.9F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(131, 120).addBox(5.9F, 23.4F, -7.6F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(131, 120).addBox(5.9F, 23.4F, 5.9F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(0, 90).addBox(-8.0F, 21.0F, -7.7F, 16.0F, 2.4F, 15.7F, new CubeDeformation(0.0F))
            .texOffs(0, 25).addBox(-7.75F, 17.0F, -7.3F, 15.5F, 4.0F, 15.3F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(0, 55).addBox(-7.4F, 17.3F, -7.6F, 14.8F, 3.4F, 0.35F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(65, 90).addBox(-8.0F, 16.3F, -8.0F, 16.0F, 0.7F, 16.0F, new CubeDeformation(0.0F))
            .texOffs(0, 0).addBox(-8.0F, 4.5F, -6.6F, 1.8F, 11.8F, 12.2F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(135, 90).addBox(-6.225F, 4.5F, -2.675F, 0.35F, 11.8F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(135, 90).addBox(-6.225F, 4.5F, 2.325F, 0.35F, 11.8F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(29, 0).addBox(6.2F, 4.5F, -6.6F, 1.8F, 11.8F, 12.2F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(135, 90).addBox(5.875F, 4.5F, -2.675F, 0.35F, 11.8F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(135, 90).addBox(5.875F, 4.5F, 2.325F, 0.35F, 11.8F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(63, 25).addBox(-6.2F, 4.5F, 5.6F, 12.4F, 11.8F, 2.4F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(58, 0).addBox(-8.0F, 0.0F, -8.0F, 16.0F, 4.5F, 16.0F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(131, 90).addBox(-5.55F, 4.5F, -4.95F, 0.5F, 11.8F, 0.5F, new CubeDeformation(0.0F))
            .texOffs(131, 90).addBox(-5.55F, 4.5F, 4.85F, 0.5F, 11.8F, 0.5F, new CubeDeformation(0.0F))
            .texOffs(131, 90).addBox(5.05F, 4.5F, -4.95F, 0.5F, 11.8F, 0.5F, new CubeDeformation(0.0F))
            .texOffs(131, 90).addBox(5.05F, 4.5F, 4.85F, 0.5F, 11.8F, 0.5F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        fossilIdentifyingChamber.addOrReplaceChild("glass", CubeListBuilder.create()
            .texOffs(138, 90).addBox(-5.05F, 4.5F, -4.75F, 10.1F, 11.8F, 0.15F, new CubeDeformation(0.0F))
            .texOffs(160, 90).addBox(-5.05F, 4.5F, 5.0F, 10.1F, 11.8F, 0.15F, new CubeDeformation(0.0F))
            .texOffs(187, 50).addBox(-5.25F, 4.5F, -4.5F, 0.15F, 11.8F, 9.4F, new CubeDeformation(0.0F))
            .texOffs(187, 50).addBox(5.1F, 4.5F, -4.5F, 0.15F, 11.8F, 9.4F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition specimen = fossilIdentifyingChamber.addOrReplaceChild("specimen", CubeListBuilder.create()
            .texOffs(29, 120).addBox(-3.5F, -0.3F, -1.4497F, 7.0F, 0.6F, 2.8995F, new CubeDeformation(0.0F))
            .texOffs(167, 110).addBox(-1.4497F, -0.312F, -3.5F, 2.8995F, 0.624F, 7.0F, new CubeDeformation(0.0F))
            .texOffs(83, 120).addBox(-3.1F, -0.42F, -1.2841F, 6.2F, 0.12F, 2.5681F, new CubeDeformation(0.0F))
            .texOffs(225, 110).addBox(-1.2841F, -0.432F, -3.1F, 2.5681F, 0.144F, 6.2F, new CubeDeformation(0.0F))
            .texOffs(219, 120).addBox(2.35F, -0.52F, -0.15F, 0.5F, 0.1F, 0.3F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 16.0F, 0.2F));

        specimen.addOrReplaceChild("turntable_r1", CubeListBuilder.create()
            .texOffs(50, 120).addBox(-3.5F, -0.624F, -1.4497F, 7.0F, 0.648F, 2.8995F, new CubeDeformation(0.0F))
            .texOffs(188, 110).addBox(-1.4497F, -0.636F, -3.5F, 2.8995F, 0.672F, 7.0F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.3F, 0.0F, 0.0F, 0.7854F, 0.0F));

        specimen.addOrReplaceChild("turntable_top_r1", CubeListBuilder.create()
            .texOffs(102, 120).addBox(-3.1F, -0.144F, -1.2841F, 6.2F, 0.168F, 2.5681F, new CubeDeformation(0.0F))
            .texOffs(0, 120).addBox(-1.2841F, -0.156F, -3.1F, 2.5681F, 0.192F, 6.2F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -0.3F, 0.0F, 0.0F, 0.7854F, 0.0F));

        PartDefinition skull = specimen.addOrReplaceChild("skull", CubeListBuilder.create()
            .texOffs(71, 120).addBox(-1.3F, -1.62F, -1.2F, 2.6F, 1.6F, 2.4F, new CubeDeformation(0.0F))
            .texOffs(139, 120).addBox(-2.9F, -1.02F, -0.7F, 1.8F, 1.0F, 1.4F, new CubeDeformation(0.0F))
            .texOffs(203, 120).addBox(-3.45F, -0.82F, -0.45F, 0.7F, 0.8F, 0.9F, new CubeDeformation(0.0F))
            .texOffs(208, 120).addBox(-2.6F, -1.8F, -0.2F, 0.4F, 0.8F, 0.4F, new CubeDeformation(0.0F))
            .texOffs(222, 120).addBox(-1.0F, -1.45F, -1.28F, 0.7F, 0.55F, 0.06F, new CubeDeformation(0.0F))
            .texOffs(222, 120).addBox(-1.0F, -1.45F, 1.22F, 0.7F, 0.55F, 0.06F, new CubeDeformation(0.0F))
            .texOffs(121, 120).addBox(-1.8F, -0.32F, -1.0F, 2.4F, 0.4F, 2.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -0.4F, 0.0F));

        skull.addOrReplaceChild("frill", CubeListBuilder.create()
            .texOffs(19, 120).addBox(0.075F, -2.6F, -1.8F, 0.45F, 2.8F, 3.6F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(1.3F, -0.6F, 0.0F, 0.0F, 0.0F, -0.6109F));

        skull.addOrReplaceChild("brow_horn_l", CubeListBuilder.create()
            .texOffs(147, 120).addBox(-0.2F, -2.0F, -0.2F, 0.4F, 2.0F, 0.4F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-0.4F, -1.5F, -0.7F, 0.0F, 0.0F, 0.6981F));

        skull.addOrReplaceChild("brow_horn_r", CubeListBuilder.create()
            .texOffs(147, 120).addBox(-0.2F, -2.0F, -0.2F, 0.4F, 2.0F, 0.4F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(-0.4F, -1.5F, 0.7F, 0.0F, 0.0F, 0.6981F));

        PartDefinition scannerCarriage = fossilIdentifyingChamber.addOrReplaceChild("scanner_carriage", CubeListBuilder.create()
            .texOffs(209, 110).addBox(-6.2F, -0.7F, -3.1F, 0.9F, 1.4F, 6.2F, new CubeDeformation(0.0F))
            .texOffs(209, 110).addBox(5.3F, -0.7F, -3.1F, 0.9F, 1.4F, 6.2F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 5.8F, 0.2F));

        scannerCarriage.addOrReplaceChild("scanner_ring", CubeListBuilder.create()
            .texOffs(150, 120).addBox(-5.3F, -0.3F, -5.45F, 10.6F, 0.6F, 0.45F, new CubeDeformation(0.0F))
            .texOffs(174, 120).addBox(-5.3F, -0.3F, 4.8F, 10.6F, 0.6F, 0.45F, new CubeDeformation(0.0F))
            .texOffs(182, 90).addBox(-5.3F, -0.3F, -5.0F, 0.45F, 0.6F, 9.8F, new CubeDeformation(0.0F))
            .texOffs(182, 90).addBox(4.85F, -0.3F, -5.0F, 0.45F, 0.6F, 9.8F, new CubeDeformation(0.0F))
            .texOffs(198, 120).addBox(-3.1F, -0.5F, -5.95F, 1.2F, 1.0F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(198, 120).addBox(1.9F, -0.5F, -5.95F, 1.2F, 1.0F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(204, 90).addBox(-4.85F, 0.26F, -4.95F, 9.7F, 0.06F, 9.7F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition controlPanel = fossilIdentifyingChamber.addOrReplaceChild("control_panel", CubeListBuilder.create()
            .texOffs(31, 55).addBox(-6.5F, 0.4F, -8.05F, 13.0F, 3.6F, 0.1F, new CubeDeformation(0.0F), 0.5F, 0.5F), PartPose.offset(0.0F, 0.0F, 0.0F));

        controlPanel.addOrReplaceChild("console_r1", CubeListBuilder.create()
            .texOffs(58, 55).addBox(-5.0F, -1.3F, -1.3F, 10.0F, 1.3F, 2.4F, new CubeDeformation(0.0F), 0.5F, 0.5F), PartPose.offsetAndRotation(0.0F, 16.3F, -6.4F, 0.384F, 0.0F, 0.0F));

        PartDefinition statusLights = fossilIdentifyingChamber.addOrReplaceChild("status_lights", CubeListBuilder.create()
            .texOffs(211, 120).addBox(-1.4F, -0.4F, 0.03F, 2.9F, 0.8F, 0.1F, new CubeDeformation(0.0F)), PartPose.offset(5.7F, 19.0F, -7.75F));

        statusLights.addOrReplaceChild("status_light_0", CubeListBuilder.create()
            .texOffs(225, 120).addBox(-0.275F, -0.25F, -0.15F, 0.55F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(-0.9F, 0.0F, 0.0F));

        statusLights.addOrReplaceChild("status_light_1", CubeListBuilder.create()
            .texOffs(228, 120).addBox(-0.275F, -0.25F, -0.15F, 0.55F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        statusLights.addOrReplaceChild("status_light_2", CubeListBuilder.create()
            .texOffs(231, 120).addBox(-0.275F, -0.25F, -0.15F, 0.55F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(0.9F, 0.0F, 0.0F));

        return LayerDefinition.create(meshdefinition, 256, 128);
    }

    @Override
    public void setupAnim(FossilIdentificationChamberRenderState state) {
        super.setupAnim(state);
        this.idleAnimation.apply((long) (state.ageInTicks * 50.0F), 1.0F);
        this.processingAnimation.apply(state.identifyingState, state.ageInTicks);
    }
}
