package com.coolerpromc.ancientcreature.client.entity.model.block;

import com.coolerpromc.ancientcreature.client.entity.animation.block.GenomeSequencerAnimation;
import com.coolerpromc.ancientcreature.client.entity.state.block.GenomeSequencerRenderState;
import net.minecraft.client.animation.KeyframeAnimation;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

// Generated by art/texgen/machines/make_machines.py from art/texgen/machines/defs/genome_sequencer.py - edit that, not this file.
public class GenomeSequencerModel extends EntityModel<GenomeSequencerRenderState> {
    private final KeyframeAnimation processingAnimation;
    private final KeyframeAnimation idleAnimation;

    public GenomeSequencerModel(ModelPart root) {
        super(root);
        this.processingAnimation = GenomeSequencerAnimation.PROCESSING.bake(root);
        this.idleAnimation = GenomeSequencerAnimation.IDLE.bake(root);
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();

        PartDefinition genomeSequencer = partdefinition.addOrReplaceChild("genome_sequencer", CubeListBuilder.create(), PartPose.offset(0.0F, 24.0F, 0.0F));

        genomeSequencer.addOrReplaceChild("chassis", CubeListBuilder.create()
            .texOffs(233, 94).addBox(-7.6F, -0.6F, -7.6F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(233, 94).addBox(-7.6F, -0.6F, 5.9F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(233, 94).addBox(5.9F, -0.6F, -7.6F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(233, 94).addBox(5.9F, -0.6F, 5.9F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(77, 48).addBox(-8.0F, -3.0F, -7.7F, 16.0F, 2.4F, 15.7F, new CubeDeformation(0.0F))
            .texOffs(54, 0).addBox(-7.75F, -8.2F, -7.3F, 15.5F, 5.2F, 15.3F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(0, 0).addBox(-7.75F, -19.8F, -7.0F, 1.4F, 11.6F, 11.4F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(27, 0).addBox(6.35F, -19.8F, -7.0F, 1.4F, 11.6F, 11.4F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(0, 24).addBox(-7.75F, -19.8F, 4.4F, 15.5F, 11.6F, 3.35F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(125, 80).addBox(-6.35F, -19.8F, 4.2F, 12.7F, 11.6F, 0.2F, new CubeDeformation(0.0F))
            .texOffs(142, 48).addBox(-8.0F, -22.2F, -7.4F, 16.0F, 2.4F, 15.4F, new CubeDeformation(0.0F))
            .texOffs(76, 80).addBox(-6.35F, -8.7F, -7.0F, 12.7F, 0.5F, 11.2F, new CubeDeformation(0.0F))
            .texOffs(152, 80).addBox(-6.35F, -19.8F, -7.05F, 12.7F, 11.1F, 0.15F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition chamber = genomeSequencer.addOrReplaceChild("chamber", CubeListBuilder.create(), PartPose.offset(0.0F, -8.7F, -0.6F));

        PartDefinition analysisRing = chamber.addOrReplaceChild("analysis_ring", CubeListBuilder.create()
            .texOffs(40, 94).addBox(-3.7F, -1.0F, -1.5326F, 7.4F, 1.0F, 3.0652F, new CubeDeformation(0.0F))
            .texOffs(185, 80).addBox(-1.5326F, -1.012F, -3.7F, 3.0652F, 1.024F, 7.4F, new CubeDeformation(0.0F))
            .texOffs(106, 94).addBox(-3.3F, -1.3F, -1.3669F, 6.6F, 0.3F, 2.7338F, new CubeDeformation(0.0F))
            .texOffs(0, 94).addBox(-1.3669F, -1.312F, -3.3F, 2.7338F, 0.324F, 6.6F, new CubeDeformation(0.0F))
            .texOffs(249, 94).addBox(-0.6F, -2.9F, -0.6F, 1.2F, 1.6F, 1.2F, new CubeDeformation(0.0F))
            .texOffs(155, 94).addBox(-0.4F, -3.9F, -3.0F, 0.8F, 2.6F, 0.8F, new CubeDeformation(0.0F))
            .texOffs(0, 102).addBox(-0.3F, -3.15F, -2.9F, 0.6F, 1.8F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(23, 102).addBox(-0.475F, -4.25F, -3.075F, 0.95F, 0.35F, 0.95F, new CubeDeformation(0.0F))
            .texOffs(155, 94).addBox(1.4385F, -3.9F, -2.2385F, 0.8F, 2.6F, 0.8F, new CubeDeformation(0.0F))
            .texOffs(4, 102).addBox(1.5385F, -3.15F, -2.1385F, 0.6F, 1.8F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(28, 102).addBox(1.3635F, -4.25F, -2.3135F, 0.95F, 0.35F, 0.95F, new CubeDeformation(0.0F))
            .texOffs(155, 94).addBox(2.2F, -3.9F, -0.4F, 0.8F, 2.6F, 0.8F, new CubeDeformation(0.0F))
            .texOffs(8, 102).addBox(2.3F, -3.15F, -0.3F, 0.6F, 1.8F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(33, 102).addBox(2.125F, -4.25F, -0.475F, 0.95F, 0.35F, 0.95F, new CubeDeformation(0.0F))
            .texOffs(155, 94).addBox(1.4385F, -3.9F, 1.4385F, 0.8F, 2.6F, 0.8F, new CubeDeformation(0.0F))
            .texOffs(12, 102).addBox(1.5385F, -3.15F, 1.5385F, 0.6F, 1.8F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(38, 102).addBox(1.3635F, -4.25F, 1.3635F, 0.95F, 0.35F, 0.95F, new CubeDeformation(0.0F))
            .texOffs(155, 94).addBox(-0.4F, -3.9F, 2.2F, 0.8F, 2.6F, 0.8F, new CubeDeformation(0.0F))
            .texOffs(0, 102).addBox(-0.3F, -3.15F, 2.3F, 0.6F, 1.8F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(23, 102).addBox(-0.475F, -4.25F, 2.125F, 0.95F, 0.35F, 0.95F, new CubeDeformation(0.0F))
            .texOffs(155, 94).addBox(-2.2385F, -3.9F, 1.4385F, 0.8F, 2.6F, 0.8F, new CubeDeformation(0.0F))
            .texOffs(4, 102).addBox(-2.1385F, -3.15F, 1.5385F, 0.6F, 1.8F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(28, 102).addBox(-2.3135F, -4.25F, 1.3635F, 0.95F, 0.35F, 0.95F, new CubeDeformation(0.0F))
            .texOffs(155, 94).addBox(-3.0F, -3.9F, -0.4F, 0.8F, 2.6F, 0.8F, new CubeDeformation(0.0F))
            .texOffs(8, 102).addBox(-2.9F, -3.15F, -0.3F, 0.6F, 1.8F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(33, 102).addBox(-3.075F, -4.25F, -0.475F, 0.95F, 0.35F, 0.95F, new CubeDeformation(0.0F))
            .texOffs(155, 94).addBox(-2.2385F, -3.9F, -2.2385F, 0.8F, 2.6F, 0.8F, new CubeDeformation(0.0F))
            .texOffs(12, 102).addBox(-2.1385F, -3.15F, -2.1385F, 0.6F, 1.8F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(38, 102).addBox(-2.3135F, -4.25F, -2.3135F, 0.95F, 0.35F, 0.95F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        analysisRing.addOrReplaceChild("carousel_r1", CubeListBuilder.create()
            .texOffs(62, 94).addBox(-3.7F, -1.024F, -1.5326F, 7.4F, 1.048F, 3.0652F, new CubeDeformation(0.0F))
            .texOffs(207, 80).addBox(-1.5326F, -1.036F, -3.7F, 3.0652F, 1.072F, 7.4F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.7854F, 0.0F));

        analysisRing.addOrReplaceChild("carousel_top_r1", CubeListBuilder.create()
            .texOffs(126, 94).addBox(-3.3F, -0.324F, -1.3669F, 6.6F, 0.348F, 2.7338F, new CubeDeformation(0.0F))
            .texOffs(20, 94).addBox(-1.3669F, -0.336F, -3.3F, 2.7338F, 0.372F, 6.6F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, -1.0F, 0.0F, 0.0F, 0.7854F, 0.0F));

        chamber.addOrReplaceChild("mounts", CubeListBuilder.create()
            .texOffs(16, 102).addBox(-0.8F, -0.8F, 3.4F, 1.6F, 0.8F, 1.2F, new CubeDeformation(0.0F))
            .texOffs(179, 80).addBox(-0.225F, -10.6F, 3.775F, 0.45F, 9.8F, 0.45F, new CubeDeformation(0.0F))
            .texOffs(182, 80).addBox(-1.15F, -10.6F, 3.85F, 0.3F, 9.8F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(182, 80).addBox(0.85F, -10.6F, 3.85F, 0.3F, 9.8F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(223, 94).addBox(-1.5F, -11.1F, 3.3F, 3.0F, 0.8F, 1.4F, new CubeDeformation(0.0F))
            .texOffs(48, 102).addBox(-1.6F, -10.3F, 3.6F, 3.2F, 0.4F, 0.6F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        chamber.addOrReplaceChild("scan_head", CubeListBuilder.create()
            .texOffs(229, 80).addBox(-0.7F, -0.4F, 0.0F, 1.4F, 0.8F, 6.6F, new CubeDeformation(0.0F))
            .texOffs(146, 94).addBox(-0.9F, -0.2F, -0.9F, 1.8F, 1.8F, 1.8F, new CubeDeformation(0.0F))
            .texOffs(43, 102).addBox(-0.45F, 1.6F, -0.45F, 0.9F, 0.4F, 0.9F, new CubeDeformation(0.0F))
            .texOffs(73, 102).addBox(-0.175F, 2.0F, -0.175F, 0.35F, 0.65F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(241, 94).addBox(-1.2F, -0.8F, 6.1F, 2.4F, 1.2F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -6.9F, -2.6F));

        genomeSequencer.addOrReplaceChild("cartridge_tray", CubeListBuilder.create()
            .texOffs(189, 94).addBox(-3.8F, -1.3F, -0.45F, 7.6F, 2.2F, 0.45F, new CubeDeformation(0.0F))
            .texOffs(65, 102).addBox(-1.4F, -0.25F, -0.75F, 2.8F, 0.45F, 0.35F, new CubeDeformation(0.0F))
            .texOffs(84, 94).addBox(-3.5F, 0.2F, 0.0F, 7.0F, 0.3F, 3.0F, new CubeDeformation(0.0F))
            .texOffs(207, 94).addBox(-2.4F, -0.05F, 0.3F, 4.8F, 0.25F, 2.2F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -4.5F, -7.3F));

        PartDefinition controls = genomeSequencer.addOrReplaceChild("controls", CubeListBuilder.create()
            .texOffs(160, 94).addBox(-6.3F, -23.8F, -2.9F, 12.6F, 1.6F, 1.0F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        controls.addOrReplaceChild("touchscreen_r1", CubeListBuilder.create()
            .texOffs(0, 40).addBox(-6.5F, -0.6F, 0.0F, 13.0F, 0.6F, 5.6F, new CubeDeformation(0.0F), 0.5F, 0.5F), PartPose.offsetAndRotation(0.0F, -22.2F, -7.4F, 0.3142F, 0.0F, 0.0F));

        PartDefinition statusLights = controls.addOrReplaceChild("status_lights", CubeListBuilder.create()
            .texOffs(57, 102).addBox(-0.5F, -0.6F, 0.0F, 3.2F, 0.8F, 0.1F, new CubeDeformation(0.0F)), PartPose.offset(4.6F, -6.7F, -7.4F));

        statusLights.addOrReplaceChild("status_light_0", CubeListBuilder.create()
            .texOffs(76, 102).addBox(-0.25F, -0.25F, -0.15F, 0.5F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -0.2F, -0.05F));

        statusLights.addOrReplaceChild("status_light_1", CubeListBuilder.create()
            .texOffs(79, 102).addBox(-0.25F, -0.25F, -0.15F, 0.5F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(0.8F, -0.2F, -0.05F));

        statusLights.addOrReplaceChild("status_light_2", CubeListBuilder.create()
            .texOffs(82, 102).addBox(-0.25F, -0.25F, -0.15F, 0.5F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(1.6F, -0.2F, -0.05F));

        statusLights.addOrReplaceChild("status_light_3", CubeListBuilder.create()
            .texOffs(85, 102).addBox(-0.25F, -0.25F, -0.15F, 0.5F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(2.4F, -0.2F, -0.05F));

        return LayerDefinition.create(meshdefinition, 256, 128);
    }

    @Override
    public void setupAnim(GenomeSequencerRenderState state) {
        super.setupAnim(state);
        this.idleAnimation.apply((long) (state.ageInTicks * 50.0F), 1.0F);
        this.processingAnimation.apply(state.processingState, state.ageInTicks);
    }
}
