package com.coolerpromc.ancientcreature.client.entity.model.block;

import com.coolerpromc.ancientcreature.client.entity.animation.block.IncubatorAnimation;
import com.coolerpromc.ancientcreature.client.entity.state.block.IncubatorRenderState;
import net.minecraft.client.animation.KeyframeAnimation;
import net.minecraft.client.model.EntityModel;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;

// Generated by art/texgen/machines/make_machines.py from art/texgen/machines/defs/incubator.py - edit that, not this file.
public class IncubatorModel extends EntityModel<IncubatorRenderState> {
    private final KeyframeAnimation processingAnimation;
    private final KeyframeAnimation idleAnimation;

    public IncubatorModel(ModelPart root) {
        super(root);
        this.processingAnimation = IncubatorAnimation.PROCESSING.bake(root);
        this.idleAnimation = IncubatorAnimation.IDLE.bake(root);
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition meshdefinition = new MeshDefinition();
        PartDefinition partdefinition = meshdefinition.getRoot();

        PartDefinition incubator = partdefinition.addOrReplaceChild("incubator", CubeListBuilder.create(), PartPose.offset(0.0F, 24.0F, 0.0F));

        incubator.addOrReplaceChild("cabinet", CubeListBuilder.create()
            .texOffs(225, 112).addBox(-7.6F, -0.6F, -7.6F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(225, 112).addBox(-7.6F, -0.6F, 5.9F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(225, 112).addBox(5.9F, -0.6F, -7.6F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(225, 112).addBox(5.9F, -0.6F, 5.9F, 1.7F, 0.6F, 1.7F, new CubeDeformation(0.0F))
            .texOffs(76, 58).addBox(-8.0F, -2.6F, -7.7F, 16.0F, 2.0F, 15.7F, new CubeDeformation(0.0F))
            .texOffs(141, 58).addBox(-8.0F, -4.0F, -7.4F, 16.0F, 1.4F, 15.4F, new CubeDeformation(0.0F))
            .texOffs(0, 0).addBox(-8.0F, -19.0F, -7.4F, 1.4F, 15.0F, 12.8F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(29, 0).addBox(6.6F, -19.0F, -7.4F, 1.4F, 15.0F, 12.8F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(0, 29).addBox(-8.0F, -19.0F, 5.4F, 16.0F, 15.0F, 2.6F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(205, 58).addBox(-6.6F, -19.0F, 5.1F, 13.2F, 15.0F, 0.3F, new CubeDeformation(0.0F))
            .texOffs(25, 96).addBox(-6.6F, -4.4F, -7.0F, 13.2F, 0.4F, 12.1F, new CubeDeformation(0.0F))
            .texOffs(77, 96).addBox(-6.6F, -19.0F, -7.0F, 13.2F, 0.4F, 12.1F, new CubeDeformation(0.0F))
            .texOffs(0, 112).addBox(-5.6F, -5.2F, -1.0F, 11.2F, 0.8F, 5.2F, new CubeDeformation(0.0F))
            .texOffs(34, 112).addBox(-5.3F, -5.35F, -0.7F, 10.6F, 0.85F, 4.6F, new CubeDeformation(0.0F))
            .texOffs(58, 0).addBox(-8.0F, -24.0F, -7.6F, 16.0F, 5.0F, 15.6F, new CubeDeformation(0.0F), 0.5F, 0.5F), PartPose.offset(0.0F, 0.0F, 0.0F));

        incubator.addOrReplaceChild("door", CubeListBuilder.create()
            .texOffs(234, 58).addBox(0.0F, -7.5F, -0.3F, 0.9F, 15.0F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(234, 58).addBox(12.3F, -7.5F, -0.3F, 0.9F, 15.0F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(0, 120).addBox(0.9F, 6.6F, -0.3F, 11.4F, 0.9F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(0, 120).addBox(0.9F, -7.5F, -0.3F, 11.4F, 0.9F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(0, 96).addBox(0.9F, -6.6F, -0.1F, 11.4F, 13.2F, 0.15F, new CubeDeformation(0.0F))
            .texOffs(81, 112).addBox(12.6F, -2.5F, -1.1F, 0.5F, 4.5F, 0.5F, new CubeDeformation(0.0F))
            .texOffs(134, 120).addBox(12.6F, 1.5F, -0.7F, 0.5F, 0.5F, 0.4F, new CubeDeformation(0.0F))
            .texOffs(134, 120).addBox(12.6F, -2.5F, -0.7F, 0.5F, 0.5F, 0.4F, new CubeDeformation(0.0F))
            .texOffs(245, 112).addBox(-0.4F, 3.9F, -0.2F, 0.5F, 1.6F, 0.6F, new CubeDeformation(0.0F))
            .texOffs(245, 112).addBox(-0.4F, -5.5F, -0.2F, 0.5F, 1.6F, 0.6F, new CubeDeformation(0.0F)), PartPose.offset(-6.6F, -11.5F, -7.3F));

        PartDefinition eggTray = incubator.addOrReplaceChild("egg_tray", CubeListBuilder.create()
            .texOffs(166, 96).addBox(-5.6F, 0.4F, -3.4F, 11.2F, 0.4F, 7.4F, new CubeDeformation(0.0F))
            .texOffs(149, 96).addBox(-3.75F, -0.5F, -3.4F, 0.3F, 0.9F, 7.4F, new CubeDeformation(0.0F))
            .texOffs(149, 96).addBox(-1.35F, -0.5F, -3.4F, 0.3F, 0.9F, 7.4F, new CubeDeformation(0.0F))
            .texOffs(149, 96).addBox(1.05F, -0.5F, -3.4F, 0.3F, 0.9F, 7.4F, new CubeDeformation(0.0F))
            .texOffs(149, 96).addBox(3.45F, -0.5F, -3.4F, 0.3F, 0.9F, 7.4F, new CubeDeformation(0.0F))
            .texOffs(241, 112).addBox(-0.3F, 0.8F, -0.3F, 0.6F, 1.6F, 0.6F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -8.4F, -1.0F));

        eggTray.addOrReplaceChild("eggs", CubeListBuilder.create()
            .texOffs(69, 120).addBox(-2.9338F, -0.3778F, -0.5125F, 1.0677F, 0.3778F, 1.025F, new CubeDeformation(0.0F))
            .texOffs(233, 112).addBox(-3.2528F, -0.7556F, -0.8187F, 1.7057F, 0.3778F, 1.6375F, new CubeDeformation(0.0F))
            .texOffs(145, 112).addBox(-3.3998F, -1.1333F, -0.9598F, 1.9996F, 0.3778F, 1.9196F, new CubeDeformation(0.0F))
            .texOffs(105, 112).addBox(-3.4496F, -1.5111F, -1.0076F, 2.0992F, 0.3778F, 2.0152F, new CubeDeformation(0.0F))
            .texOffs(125, 112).addBox(-3.4353F, -1.8889F, -0.9939F, 2.0706F, 0.3778F, 1.9878F, new CubeDeformation(0.0F))
            .texOffs(172, 112).addBox(-3.3829F, -2.2667F, -0.9435F, 1.9657F, 0.3778F, 1.8871F, new CubeDeformation(0.0F))
            .texOffs(217, 112).addBox(-3.2857F, -2.6444F, -0.8503F, 1.7715F, 0.3778F, 1.7006F, new CubeDeformation(0.0F))
            .texOffs(49, 120).addBox(-3.1262F, -3.0222F, -0.6972F, 1.4525F, 0.3778F, 1.3944F, new CubeDeformation(0.0F))
            .texOffs(85, 120).addBox(-2.8413F, -3.4F, -0.4236F, 0.8825F, 0.3778F, 0.8472F, new CubeDeformation(0.0F))
            .texOffs(75, 120).addBox(-0.5084F, -0.3444F, -0.8881F, 1.0168F, 0.3444F, 0.9762F, new CubeDeformation(0.0F))
            .texOffs(34, 120).addBox(-0.8122F, -0.6889F, -1.1797F, 1.6245F, 0.3444F, 1.5595F, new CubeDeformation(0.0F))
            .texOffs(181, 112).addBox(-0.9522F, -1.0333F, -1.3141F, 1.9043F, 0.3444F, 1.8282F, new CubeDeformation(0.0F))
            .texOffs(154, 112).addBox(-0.9996F, -1.3778F, -1.3596F, 1.9992F, 0.3444F, 1.9193F, new CubeDeformation(0.0F))
            .texOffs(163, 112).addBox(-0.986F, -1.7222F, -1.3466F, 1.972F, 0.3444F, 1.8931F, new CubeDeformation(0.0F))
            .texOffs(190, 112).addBox(-0.9361F, -2.0667F, -1.2986F, 1.8721F, 0.3444F, 1.7972F, new CubeDeformation(0.0F))
            .texOffs(26, 120).addBox(-0.8436F, -2.4111F, -1.2098F, 1.6871F, 0.3444F, 1.6196F, new CubeDeformation(0.0F))
            .texOffs(56, 120).addBox(-0.6917F, -2.7556F, -1.064F, 1.3833F, 0.3444F, 1.328F, new CubeDeformation(0.0F))
            .texOffs(90, 120).addBox(-0.4203F, -3.1F, -0.8034F, 0.8405F, 0.3444F, 0.8069F, new CubeDeformation(0.0F))
            .texOffs(63, 120).addBox(1.8407F, -0.4F, -0.1369F, 1.1185F, 0.4F, 1.0738F, new CubeDeformation(0.0F))
            .texOffs(208, 112).addBox(1.5065F, -0.8F, -0.4577F, 1.7869F, 0.4F, 1.7154F, new CubeDeformation(0.0F))
            .texOffs(115, 112).addBox(1.3526F, -1.2F, -0.6055F, 2.0948F, 0.4F, 2.011F, new CubeDeformation(0.0F))
            .texOffs(85, 112).addBox(1.3004F, -1.6F, -0.6556F, 2.1992F, 0.4F, 2.1112F, new CubeDeformation(0.0F))
            .texOffs(95, 112).addBox(1.3154F, -2.0F, -0.6412F, 2.1692F, 0.4F, 2.0825F, new CubeDeformation(0.0F))
            .texOffs(135, 112).addBox(1.3703F, -2.4F, -0.5885F, 2.0593F, 0.4F, 1.9769F, new CubeDeformation(0.0F))
            .texOffs(199, 112).addBox(1.4721F, -2.8F, -0.4908F, 1.8558F, 0.4F, 1.7816F, new CubeDeformation(0.0F))
            .texOffs(42, 120).addBox(1.6392F, -3.2F, -0.3304F, 1.5217F, 0.4F, 1.4608F, new CubeDeformation(0.0F))
            .texOffs(80, 120).addBox(1.9377F, -3.6F, -0.0438F, 0.9246F, 0.4F, 0.8876F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.4F, 0.0F));

        PartDefinition fanRotor = incubator.addOrReplaceChild("fan_rotor", CubeListBuilder.create()
            .texOffs(95, 120).addBox(-0.5F, -0.5F, -0.25F, 1.0F, 1.0F, 0.5F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -13.0F, 4.8F));

        fanRotor.addOrReplaceChild("fan_blade_0", CubeListBuilder.create()
            .texOffs(100, 120).addBox(-0.4F, -1.9F, -0.05F, 0.8F, 1.45F, 0.12F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 0.3491F));

        fanRotor.addOrReplaceChild("fan_blade_1", CubeListBuilder.create()
            .texOffs(100, 120).addBox(-0.4F, -1.9F, -0.05F, 0.8F, 1.45F, 0.12F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 1.9199F));

        fanRotor.addOrReplaceChild("fan_blade_2", CubeListBuilder.create()
            .texOffs(100, 120).addBox(-0.4F, -1.9F, -0.05F, 0.8F, 1.45F, 0.12F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 3.4907F));

        fanRotor.addOrReplaceChild("fan_blade_3", CubeListBuilder.create()
            .texOffs(100, 120).addBox(-0.4F, -1.9F, -0.05F, 0.8F, 1.45F, 0.12F, new CubeDeformation(0.0F)), PartPose.offsetAndRotation(0.0F, 0.0F, 0.0F, 0.0F, 0.0F, 5.0615F));

        incubator.addOrReplaceChild("heater_coils", CubeListBuilder.create()
            .texOffs(103, 120).addBox(-5.4F, -0.25F, -3.2F, 10.8F, 0.45F, 0.45F, new CubeDeformation(0.0F))
            .texOffs(103, 120).addBox(-5.4F, -0.25F, -0.6F, 10.8F, 0.45F, 0.45F, new CubeDeformation(0.0F))
            .texOffs(103, 120).addBox(-5.4F, -0.25F, 2.0F, 10.8F, 0.45F, 0.45F, new CubeDeformation(0.0F))
            .texOffs(103, 120).addBox(-5.4F, -0.25F, 4.6F, 10.8F, 0.45F, 0.45F, new CubeDeformation(0.0F))
            .texOffs(129, 96).addBox(-5.8F, -0.3F, -3.6F, 0.4F, 0.6F, 8.8F, new CubeDeformation(0.0F))
            .texOffs(129, 96).addBox(5.4F, -0.3F, -3.6F, 0.4F, 0.6F, 8.8F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, -18.3F, -1.0F));

        PartDefinition controls = incubator.addOrReplaceChild("controls", CubeListBuilder.create()
            .texOffs(103, 48).addBox(1.2F, -23.0F, -7.8F, 6.2F, 3.4F, 0.25F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(33, 56).addBox(-2.6F, -22.4F, -7.9F, 3.0F, 2.0F, 0.3F, new CubeDeformation(0.0F), 0.5F, 0.5F)
            .texOffs(127, 120).addBox(-6.5F, -20.5F, -7.65F, 2.8F, 0.8F, 0.1F, new CubeDeformation(0.0F)), PartPose.offset(0.0F, 0.0F, 0.0F));

        PartDefinition statusLights = controls.addOrReplaceChild("status_lights", CubeListBuilder.create(), PartPose.offset(-5.0F, -20.1F, -7.7F));

        statusLights.addOrReplaceChild("status_light_0", CubeListBuilder.create()
            .texOffs(137, 120).addBox(-0.275F, -0.25F, -0.2F, 0.55F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(-1.0F, 0.0F, 0.0F));

        statusLights.addOrReplaceChild("status_light_1", CubeListBuilder.create()
            .texOffs(140, 120).addBox(-0.275F, -0.25F, -0.2F, 0.55F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(-0.1F, 0.0F, 0.0F));

        statusLights.addOrReplaceChild("status_light_2", CubeListBuilder.create()
            .texOffs(143, 120).addBox(-0.275F, -0.25F, -0.2F, 0.55F, 0.5F, 0.2F, new CubeDeformation(0.0F)), PartPose.offset(0.8F, 0.0F, 0.0F));

        return LayerDefinition.create(meshdefinition, 256, 128);
    }

    @Override
    public void setupAnim(IncubatorRenderState state) {
        super.setupAnim(state);
        this.idleAnimation.apply((long) (state.ageInTicks * 50.0F), 1.0F);
        this.processingAnimation.apply(state.processingState, state.ageInTicks);
    }
}
